// packages/vue/src/components/Tooltip.vue
<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from 'vue';
import { cva } from 'class-variance-authority';
import { cn } from '../lib/utils';

const tooltipVariants = cva(
  'absolute z-50 px-3 py-1 text-sm rounded-md shadow-lg pointer-events-none w-max max-w-xs break-words animate-in fade-in-0 zoom-in-95',
  {
    variants: {
      variant: {
        default: 'bg-krds-gray-90 text-white',
        light: 'bg-white text-krds-gray-90 border border-krds-gray-20',
      },
      position: {
        top: 'bottom-full left-1/2 -translate-x-1/2 mb-2 before:content-[""] before:absolute before:top-full before:left-1/2 before:-translate-x-1/2 before:border-[6px] before:border-transparent',
        bottom: 'top-full left-1/2 -translate-x-1/2 mt-2 before:content-[""] before:absolute before:bottom-full before:left-1/2 before:-translate-x-1/2 before:border-[6px] before:border-transparent',
        left: 'right-full top-1/2 -translate-y-1/2 mr-2 before:content-[""] before:absolute before:left-full before:top-1/2 before:-translate-y-1/2 before:border-[6px] before:border-transparent',
        right: 'left-full top-1/2 -translate-y-1/2 ml-2 before:content-[""] before:absolute before:right-full before:top-1/2 before:-translate-y-1/2 before:border-[6px] before:border-transparent',
      },
    },
    compoundVariants: [
      { variant: 'default', position: 'top', class: 'before:border-t-krds-gray-90' },
      { variant: 'default', position: 'bottom', class: 'before:border-b-krds-gray-90' },
      { variant: 'default', position: 'left', class: 'before:border-l-krds-gray-90' },
      { variant: 'default', position: 'right', class: 'before:border-r-krds-gray-90' },
      { variant: 'light', position: 'top', class: 'before:border-t-white' },
      { variant: 'light', position: 'bottom', class: 'before:border-b-white' },
      { variant: 'light', position: 'left', class: 'before:border-l-white' },
      { variant: 'light', position: 'right', class: 'before:border-r-white' },
    ],
    defaultVariants: {
      variant: 'default',
      position: 'right',
    },
  }
);

const props = withDefaults(
  defineProps<{
    content: string;
    variant?: 'default' | 'light';
    position?: 'top' | 'bottom' | 'left' | 'right';
    delay?: number;
    disabled?: boolean;
    autoPosition?: boolean;
    class?: string;
    wrapperClass?: string;
  }>(),
  {
    variant: 'default',
    position: 'right',
    delay: 200,
    disabled: false,
    autoPosition: true,
  }
);

const isVisible = ref(false);
const autoPos = ref<'left' | 'right'>('right');
const wrapperRef = ref<HTMLDivElement | null>(null);
const tooltipId = `tooltip-${Math.random().toString(36).substr(2, 9)}`;
let timeoutId: ReturnType<typeof setTimeout> | null = null;

const calculatePosition = () => {
  if (!wrapperRef.value || !props.autoPosition) return;

  const rect = wrapperRef.value.getBoundingClientRect();
  const viewportWidth = window.innerWidth;
  const elementCenter = rect.left + rect.width / 2;

  if (elementCenter > viewportWidth / 2) {
    autoPos.value = 'left';
  } else {
    autoPos.value = 'right';
  }
};

const handleShow = () => {
  if (props.disabled) return;

  calculatePosition();

  if (timeoutId) {
    clearTimeout(timeoutId);
  }

  timeoutId = setTimeout(() => {
    isVisible.value = true;
  }, props.delay);
};

const handleHide = () => {
  if (timeoutId) {
    clearTimeout(timeoutId);
  }
  isVisible.value = false;
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && isVisible.value) {
    handleHide();
  }
};

onMounted(() => {
  document.addEventListener('keydown', handleKeyDown);
});

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeyDown);
  if (timeoutId) {
    clearTimeout(timeoutId);
  }
});

const finalPosition = computed(() =>
  props.position || (props.autoPosition ? autoPos.value : 'right')
);

const tooltipClasses = computed(() =>
  cn(
    tooltipVariants({ variant: props.variant, position: finalPosition.value }),
    props.class
  )
);
</script>

<template>
  <div
    ref="wrapperRef"
    :class="cn('relative inline-block', wrapperClass)"
    @mouseenter="handleShow"
    @mouseleave="handleHide"
    @focus="handleShow"
    @blur="handleHide"
  >
    <slot />

    <div
      v-if="isVisible && !disabled"
      :id="tooltipId"
      role="tooltip"
      :class="tooltipClasses"
    >
      {{ content }}
    </div>
  </div>
</template>

// packages/react/src/components/Tooltip/Tooltip.tsx
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';
import { cn } from '../../lib/utils';

/**
 * Tooltip Variants Definition
 *
 * KRDS-compliant tooltip with accessibility automation
 * Foundation Layer: Focus management + ARIA automation + Keyboard navigation
 */
const tooltipVariants = cva(
  [
    'absolute',
    'z-50',
    'px-3',
    'py-2',
    'text-sm',
    'rounded-md',
    'shadow-lg',
    'pointer-events-none',
    'max-w-xs',
    'break-words',
    'animate-in',
    'fade-in-0',
    'zoom-in-95',
  ].join(' '),
  {
    variants: {
      /**
       * Variant - Visual style
       * KRDS default: dark tooltip with white text
       */
      variant: {
        default: ['bg-gray-900', 'text-white'].join(' '),
        light: ['bg-white', 'text-gray-900', 'border', 'border-gray-200'].join(
          ' '
        ),
      },
      /**
       * Position - Tooltip placement
       */
      position: {
        top: 'bottom-full left-1/2 -translate-x-1/2 mb-2',
        bottom: 'top-full left-1/2 -translate-x-1/2 mt-2',
        left: 'right-full top-1/2 -translate-y-1/2 mr-2',
        right: 'left-full top-1/2 -translate-y-1/2 ml-2',
      },
    },
    defaultVariants: {
      variant: 'default',
      position: 'top',
    },
  }
);

/**
 * Tooltip Props Interface
 *
 * Foundation Layer auto-implementation:
 * - aria-describedby auto-connection
 * - Focus management (mouse hover + keyboard focus)
 * - ESC key handler
 */
export interface TooltipProps extends VariantProps<typeof tooltipVariants> {
  /**
   * Tooltip content text
   */
  content: React.ReactNode;

  /**
   * Child element that triggers the tooltip
   */
  children: React.ReactElement;

  /**
   * Delay before showing tooltip (ms)
   * @default 200
   */
  delay?: number;

  /**
   * Whether tooltip is disabled
   * @default false
   */
  disabled?: boolean;

  /**
   * Additional CSS classes for tooltip container
   */
  className?: string;

  /**
   * Additional CSS classes for wrapper
   */
  wrapperClassName?: string;
}

/**
 * Tooltip Component
 *
 * **Foundation Layer Features:**
 * - ✅ Focus Management: Mouse hover + keyboard focus detection
 * - ✅ ARIA Automation: aria-describedby auto-connection
 * - ✅ Keyboard Navigation: ESC key closes tooltip
 * - ✅ WCAG 2.2 Compliance: 1.4.13 Content on Hover or Focus
 *
 * **KRDS Standards:**
 * - Dark background (#1a1a1a) with white text
 * - Sufficient contrast ratio (>7:1)
 * - Hover/Focus persistent display
 *
 * @example
 * ```tsx
 * <Tooltip content="Save your changes">
 *   <Button>Save</Button>
 * </Tooltip>
 * ```
 *
 * @example
 * ```tsx
 * <Tooltip content="Delete item" position="right" variant="light">
 *   <Button variant="danger">Delete</Button>
 * </Tooltip>
 * ```
 */
export const Tooltip = React.forwardRef<HTMLDivElement, TooltipProps>(
  (
    {
      content,
      children,
      variant,
      position,
      delay = 200,
      disabled = false,
      className,
      wrapperClassName,
      ...props
    },
    ref
  ) => {
    const [isVisible, setIsVisible] = React.useState(false);
    const [tooltipId] = React.useState(
      () => `tooltip-${Math.random().toString(36).substr(2, 9)}`
    );
    const timeoutRef = React.useRef<ReturnType<typeof setTimeout> | null>(null);
    const wrapperRef = React.useRef<HTMLDivElement>(null);

    /**
     * Foundation Layer: Focus Management
     * Show tooltip on mouse enter or focus
     */
    const handleShow = React.useCallback(() => {
      if (disabled) return;

      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }

      timeoutRef.current = setTimeout(() => {
        setIsVisible(true);
      }, delay);
    }, [disabled, delay]);

    /**
     * Foundation Layer: Focus Management
     * Hide tooltip on mouse leave or blur
     */
    const handleHide = React.useCallback(() => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
      setIsVisible(false);
    }, []);

    /**
     * Foundation Layer: Keyboard Navigation
     * ESC key closes tooltip (WCAG 2.2 success criterion)
     */
    const handleKeyDown = React.useCallback(
      (event: KeyboardEvent) => {
        if (event.key === 'Escape' && isVisible) {
          handleHide();
        }
      },
      [isVisible, handleHide]
    );

    /**
     * Foundation Layer: Event Listeners Setup
     * Mouse hover + keyboard focus + ESC key
     */
    React.useEffect(() => {
      const wrapper = wrapperRef.current;
      if (!wrapper) return;

      const child = wrapper.firstElementChild as HTMLElement;
      if (!child) return;

      // Mouse events
      child.addEventListener('mouseenter', handleShow);
      child.addEventListener('mouseleave', handleHide);

      // Focus events (keyboard navigation)
      child.addEventListener('focus', handleShow);
      child.addEventListener('blur', handleHide);

      // ESC key handler
      document.addEventListener('keydown', handleKeyDown);

      return () => {
        child.removeEventListener('mouseenter', handleShow);
        child.removeEventListener('mouseleave', handleHide);
        child.removeEventListener('focus', handleShow);
        child.removeEventListener('blur', handleHide);
        document.removeEventListener('keydown', handleKeyDown);

        if (timeoutRef.current) {
          clearTimeout(timeoutRef.current);
        }
      };
    }, [handleShow, handleHide, handleKeyDown]);

    /**
     * Foundation Layer: ARIA Automation
     * Clone child with aria-describedby auto-connection
     */
    const childWithAria = React.cloneElement(children, {
      'aria-describedby': isVisible ? tooltipId : undefined,
    } as React.HTMLAttributes<HTMLElement>);

    return (
      <div
        ref={wrapperRef}
        className={cn('relative inline-block', wrapperClassName)}
        {...props}
      >
        {childWithAria}

        {/* Tooltip Content */}
        {isVisible && !disabled && (
          <div
            ref={ref}
            id={tooltipId}
            role="tooltip"
            className={cn(tooltipVariants({ variant, position }), className)}
          >
            {content}
          </div>
        )}
      </div>
    );
  }
);

Tooltip.displayName = 'Tooltip';
