// packages/vue/src/components/Select.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { ChevronDown, Check } from 'lucide-vue-next';
import { cn } from '../lib/utils';

export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

const props = withDefaults(
  defineProps<{
    options: SelectOption[];
    modelValue?: string;
    placeholder?: string;
    disabled?: boolean;
    status?: 'error' | 'success' | 'info';
    size?: 'lg' | 'md' | 'sm';
    label?: string;
    class?: string;
  }>(),
  {
    placeholder: '선택하세요',
    disabled: false,
    size: 'lg',
  }
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const isOpen = ref(false);

const sizeClasses = {
  lg: 'h-14',
  md: 'h-12',
  sm: 'h-10',
} as const;

const selectedOption = computed(() => props.options.find((opt) => opt.value === props.modelValue));

const hasError = computed(() => props.status === 'error');

const triggerClasses = computed(() =>
  cn(
    'flex w-full items-center justify-between rounded-md border bg-krds-white pl-4 pr-12 py-2 text-krds-body-lg leading-[150%] shadow-sm transition-colors relative',
    sizeClasses[props.size],
    'focus:outline-none focus:ring-2 focus:ring-krds-primary-60 focus:ring-offset-2',
    hasError.value
      ? 'border-krds-danger-60 focus:ring-krds-danger-60'
      : 'border-krds-gray-60 hover:border-krds-gray-40',
    props.disabled && 'cursor-not-allowed bg-krds-gray-5 text-krds-gray-40'
  )
);

const dropdownClasses = computed(() =>
  cn(
    'absolute z-50 max-h-96 min-w-[8rem] w-full overflow-hidden rounded-md border bg-krds-white text-krds-body-md leading-[150%] shadow-md mt-1',
    'animate-in fade-in-0 zoom-in-95'
  )
);

const handleSelect = (option: SelectOption) => {
  if (option.disabled) return;
  emit('update:modelValue', option.value);
  isOpen.value = false;
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape') {
    isOpen.value = false;
  } else if (e.key === 'Enter' || e.key === ' ') {
    isOpen.value = !isOpen.value;
  }
};

const handleClickOutside = () => {
  isOpen.value = false;
};
</script>

<template>
  <div :class="cn('relative', props.class)" v-click-outside="handleClickOutside">
    <!-- Label -->
    <label
      v-if="label"
      class="block text-krds-body-sm leading-[150%] font-medium text-krds-gray-70 mb-1"
    >
      {{ label }}
    </label>

    <!-- Trigger Button -->
    <button
      type="button"
      :class="triggerClasses"
      :disabled="disabled"
      :aria-expanded="isOpen"
      aria-haspopup="listbox"
      @click="isOpen = !isOpen"
      @keydown="handleKeyDown"
    >
      <span :class="!selectedOption && 'text-krds-gray-50'">
        {{ selectedOption?.label || placeholder }}
      </span>
      <ChevronDown
        class="h-6 w-6 absolute right-4 top-1/2 -translate-y-1/2 transition-transform"
        :class="isOpen && 'rotate-180'"
      />
    </button>

    <!-- Dropdown -->
    <Transition
      enter-active-class="transition ease-out duration-100"
      enter-from-class="opacity-0 scale-95"
      enter-to-class="opacity-100 scale-100"
      leave-active-class="transition ease-in duration-75"
      leave-from-class="opacity-100 scale-100"
      leave-to-class="opacity-0 scale-95"
    >
      <div v-if="isOpen" :class="dropdownClasses" role="listbox">
        <div class="p-1">
          <div
            v-for="option in options"
            :key="option.value"
            :class="
              cn(
                'relative flex cursor-pointer select-none items-center rounded-sm py-2 pl-8 pr-2 outline-none',
                'hover:bg-krds-primary-60 hover:text-krds-white',
                option.disabled && 'pointer-events-none opacity-50',
                option.value === modelValue && 'bg-krds-primary-5'
              )
            "
            role="option"
            :aria-selected="option.value === modelValue"
            :aria-disabled="option.disabled"
            @click="handleSelect(option)"
          >
            <!-- Check Icon -->
            <span
              v-if="option.value === modelValue"
              class="absolute left-2 flex w-4 items-center justify-center"
            >
              <Check class="h-4 w-4" />
            </span>
            {{ option.label }}
          </div>
        </div>
      </div>
    </Transition>
  </div>
</template>

// packages/react/src/components/Select/Select.tsx
import * as SelectPrimitive from '@radix-ui/react-select';
import * as React from 'react';
import { cn } from '../../lib/utils';
import { ChevronDownIcon, CheckIcon } from 'lucide-react';

/**
 * Select Option Interface
 */
export interface SelectOption<T = string> {
  value: T;
  label: string;
  disabled?: boolean;
  group?: string;
}

/**
 * Select Props Interface
 */
export interface SelectProps<T = string> {
  /**
   * Options list
   */
  options: SelectOption<T>[];

  /**
   * Selected value (or values for multiple)
   */
  value?: T | T[];

  /**
   * Change handler
   */
  onChange?: (value: T | T[]) => void;

  /**
   * Enable search/filter functionality
   * @default false
   */
  searchable?: boolean;

  /**
   * Allow multiple selection
   * @default false
   */
  multiple?: boolean;

  /**
   * Placeholder text
   */
  placeholder?: string;

  /**
   * Disabled state
   */
  disabled?: boolean;

  /**
   * Error state
   */
  error?: boolean;

  /**
   * Additional className
   */
  className?: string;

  /**
   * Custom option renderer
   */
  renderOption?: (option: SelectOption<T>) => React.ReactNode;

  /**
   * Label for the select
   */
  label?: string;
}

/**
 * Get display value
 */
function getDisplayValue<T>(
  options: SelectOption<T>[],
  value: T | T[] | undefined,
  multiple: boolean,
  placeholder?: string
): string {
  if (value === undefined || (Array.isArray(value) && value.length === 0)) {
    return placeholder || '선택하세요';
  }

  if (multiple && Array.isArray(value)) {
    const selectedOptions = options.filter((opt) => value.includes(opt.value));
    if (selectedOptions.length === 0) return placeholder || '선택하세요';
    return `${selectedOptions.length}개 선택됨`;
  }

  const selectedOption = options.find((opt) => opt.value === value);
  return selectedOption?.label || placeholder || '선택하세요';
}

/**
 * Remove value from array
 */
function removeValue<T>(values: T[], valueToRemove: T): T[] {
  return values.filter((v) => v !== valueToRemove);
}

/**
 * Select Component (Basic - Radix UI Select)
 *
 * KRDS-compliant select using Radix UI Select with full accessibility
 * Note: Multiple selection and searchable are not supported by Radix UI Select
 */
function BasicSelect<T = string>({
  options,
  value,
  onChange,
  multiple = false,
  placeholder,
  disabled = false,
  error = false,
  className,
  renderOption,
  label,
}: Omit<SelectProps<T>, 'searchable'>) {
  const selectedValue = value ?? (multiple ? [] : undefined);

  // Warn if multiple is used (Radix UI Select doesn't support multiple)
  React.useEffect(() => {
    if (multiple) {
      console.warn(
        'Select: Radix UI Select does not support multiple selection. Please use a different approach or wait for future implementation.'
      );
    }
  }, [multiple]);

  // For multiple, show warning and return placeholder
  if (multiple) {
    return (
      <div className={cn('relative', className)}>
        {label && (
          <label className="block text-[15px] leading-[150%] font-medium text-gray-700 mb-1">
            {label}
          </label>
        )}
        <div className="relative w-full cursor-not-allowed rounded-md border border-gray-300 bg-gray-50 py-2 pl-3 pr-10 text-left text-gray-400">
          <span className="block truncate">
            {getDisplayValue(options, selectedValue, multiple, placeholder)}
          </span>
        </div>
        <p className="mt-1 text-xs text-red-600">
          Multiple selection is not yet supported with Radix UI Select
        </p>
      </div>
    );
  }

  const handleValueChange = (newValue: string) => {
    onChange?.(newValue as T);
  };

  const currentValue = selectedValue as T | undefined;
  const stringValue =
    currentValue !== undefined ? String(currentValue) : undefined;

  return (
    <SelectPrimitive.Root
      value={stringValue}
      onValueChange={handleValueChange}
      disabled={disabled}
    >
      <div className={cn('relative', className)}>
        {label && (
          <label className="block text-[15px] leading-[150%] font-medium text-gray-700 mb-1">
            {label}
          </label>
        )}

        <SelectPrimitive.Trigger
          className={cn(
            'flex h-10 w-full items-center justify-between rounded-md border bg-white px-3 py-2 text-[17px] leading-[150%] shadow-sm transition-colors',
            'focus:outline-none focus:ring-2 focus:ring-[#256ef4] focus:ring-offset-2',
            error
              ? 'border-red-300 focus:ring-red-500'
              : 'border-gray-300 hover:border-gray-400',
            disabled && 'cursor-not-allowed bg-gray-50 text-gray-400',
            'data-[placeholder]:text-gray-500'
          )}
        >
          <SelectPrimitive.Value placeholder={placeholder || '선택하세요'}>
            {currentValue !== undefined
              ? options.find((opt) => opt.value === currentValue)?.label
              : null}
          </SelectPrimitive.Value>
          <SelectPrimitive.Icon>
            <ChevronDownIcon className="h-4 w-4 opacity-50" />
          </SelectPrimitive.Icon>
        </SelectPrimitive.Trigger>

        <SelectPrimitive.Portal>
          <SelectPrimitive.Content
            className={cn(
              'relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border bg-white text-[17px] leading-[150%] shadow-md',
              'data-[state=open]:animate-in data-[state=closed]:animate-out',
              'data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0',
              'data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
              'data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2',
              'data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2'
            )}
            position="popper"
          >
            <SelectPrimitive.Viewport className="p-1">
              {options.map((option) => (
                <SelectPrimitive.Item
                  key={String(option.value)}
                  value={String(option.value)}
                  disabled={option.disabled}
                  className={cn(
                    'relative flex cursor-pointer select-none items-center rounded-sm py-2 pl-8 pr-2 outline-none',
                    'focus:bg-[#256ef4] focus:text-white',
                    'data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
                    option.disabled && 'cursor-not-allowed opacity-50'
                  )}
                >
                  <SelectPrimitive.ItemIndicator className="absolute left-2 flex w-4 items-center justify-center">
                    <CheckIcon className="h-4 w-4" />
                  </SelectPrimitive.ItemIndicator>
                  <SelectPrimitive.ItemText>
                    {renderOption ? renderOption(option) : option.label}
                  </SelectPrimitive.ItemText>
                </SelectPrimitive.Item>
              ))}
            </SelectPrimitive.Viewport>
          </SelectPrimitive.Content>
        </SelectPrimitive.Portal>
      </div>
    </SelectPrimitive.Root>
  );
}

/**
 * Select Component (Searchable)
 *
 * Note: Radix UI Select does not support searchable functionality natively.
 * This is a placeholder that shows a warning and falls back to basic select.
 */
function SearchableSelect<T = string>({
  options,
  value,
  onChange,
  placeholder,
  disabled = false,
  error = false,
  className,
  renderOption,
  label,
}: Omit<SelectProps<T>, 'searchable' | 'multiple'>) {
  React.useEffect(() => {
    console.warn(
      'Select: Radix UI Select does not support searchable functionality. Using basic select instead.'
    );
  }, []);

  // Fallback to basic select
  return (
    <BasicSelect
      options={options}
      value={value}
      onChange={onChange}
      placeholder={placeholder}
      disabled={disabled}
      error={error}
      className={className}
      renderOption={renderOption}
      label={label}
    />
  );
}

/**
 * Select Component
 *
 * Unified Select component that switches between Listbox and Combobox based on searchable prop
 *
 * @example
 * ```tsx
 * // Basic Select
 * <Select
 *   options={[
 *     { value: '1', label: '서울' },
 *     { value: '2', label: '부산' }
 *   ]}
 *   value={value}
 *   onChange={setValue}
 * />
 *
 * // Searchable Select
 * <Select
 *   options={cities}
 *   value={value}
 *   onChange={setValue}
 *   searchable
 *   placeholder="도시 검색..."
 * />
 *
 * // Multiple Select
 * <Select
 *   options={cities}
 *   value={values}
 *   onChange={setValues}
 *   multiple
 * />
 * ```
 */
export function Select<T = string>(props: SelectProps<T>) {
  if (props.searchable) {
    if (props.multiple) {
      console.warn(
        'Select: searchable + multiple is not supported. Using basic multiple select.'
      );
      return <BasicSelect {...props} />;
    }
    return <SearchableSelect {...props} />;
  }

  return <BasicSelect {...props} />;
}

Select.displayName = 'Select';
