// packages/vue/src/components/Header.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { ChevronDown, Search, Menu, X } from 'lucide-vue-next';
import { cn } from '../lib/utils';
import Container from './Container.vue';

export interface UtilityLink {
  label: string;
  href: string;
}

export interface HeaderNavigationLink {
  label: string;
  href: string;
  active?: boolean;
  description?: string;
}

export interface HeaderNavigationItem {
  label: string;
  href?: string;
  active?: boolean;
  children?: HeaderNavigationLink[];
}

const props = withDefaults(
  defineProps<{
    navigationItems?: HeaderNavigationItem[];
    utilityLinks?: UtilityLink[];
    relatedSites?: UtilityLink[];
    logo?: string;
    logoAlt?: string;
    logoHref?: string;
    class?: string;
  }>(),
  {
    logo: 'https://www.krds.go.kr/resources/img/pattern/layout/head_logo.svg',
    logoAlt: '대한민국정부',
    logoHref: '/',
    utilityLinks: () => [
      { label: '로그인', href: '#' },
      { label: '회원가입', href: '#' },
      { label: 'ENGLISH', href: '#' },
    ],
    relatedSites: () => [
      { label: '건강iN', href: '#' },
      { label: 'The건강보험', href: '#' },
      { label: '요양기관업무포털', href: '#' },
    ],
  }
);

const emit = defineEmits<{
  search: [query: string];
}>();

const isMobileMenuOpen = ref(false);
const isUtilityDropdownOpen = ref(false);
const isSearchOpen = ref(false);
const searchQuery = ref('');
const openNavIndex = ref<number | null>(null);

const handleSearch = () => {
  emit('search', searchQuery.value);
  isSearchOpen.value = false;
  searchQuery.value = '';
};

const handleClickOutside = (e: MouseEvent) => {
  const target = e.target as HTMLElement;
  if (!target.closest('.utility-dropdown')) {
    isUtilityDropdownOpen.value = false;
  }
  if (!target.closest('.nav-item')) {
    openNavIndex.value = null;
  }
};

onMounted(() => {
  document.addEventListener('click', handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside);
});
</script>

<template>
  <header :class="cn('krds-header relative z-50 bg-white', props.class)">
    <!-- Utility Bar -->
    <div
      v-if="utilityLinks && utilityLinks.length > 0"
      class="border-b border-krds-gray-10 bg-krds-gray-5"
    >
      <Container class="flex justify-end">
        <ul class="flex items-center gap-4 text-sm">
          <li v-for="link in utilityLinks" :key="link.label">
            <a
              :href="link.href"
              class="text-krds-gray-70 hover:text-krds-gray-90 hover:underline py-2 inline-block"
            >
              {{ link.label }}
            </a>
          </li>
          <li v-if="relatedSites && relatedSites.length > 0" class="relative utility-dropdown">
            <button
              type="button"
              class="flex items-center gap-1 text-krds-gray-70 hover:text-krds-gray-90 py-2"
              aria-label="관련사이트 메뉴"
              :aria-expanded="isUtilityDropdownOpen"
              @click="isUtilityDropdownOpen = !isUtilityDropdownOpen"
            >
              관련사이트
              <ChevronDown
                :class="
                  cn(
                    'h-4 w-4 transition-transform',
                    isUtilityDropdownOpen && 'rotate-180'
                  )
                "
                aria-hidden="true"
              />
            </button>
            <div
              v-if="isUtilityDropdownOpen"
              class="absolute right-0 top-full mt-1 z-50 min-w-[160px] rounded-md border border-krds-gray-20 bg-white shadow-lg"
            >
              <a
                v-for="site in relatedSites"
                :key="site.label"
                :href="site.href"
                target="_blank"
                rel="noopener noreferrer"
                class="block px-4 py-2 text-sm text-krds-gray-90 hover:bg-krds-gray-5"
              >
                {{ site.label }}
                <span class="sr-only"> (새 창 열기)</span>
              </a>
            </div>
          </li>
        </ul>
      </Container>
    </div>

    <!-- Branding + Actions -->
    <div class="border-b border-krds-gray-10">
      <Container class="flex items-center justify-between py-4">
        <div class="flex items-center gap-4">
          <a
            :href="logoHref"
            class="block"
            :aria-label="`${logoAlt} 홈으로 이동`"
          >
            <img :src="logo" :alt="logoAlt" class="h-10" />
          </a>
          <slot name="slogan" />
        </div>

        <!-- Actions -->
        <div class="flex items-center gap-2">
          <button
            type="button"
            class="p-2 rounded-md hover:bg-krds-gray-5 focus:outline-none focus:ring-2 focus:ring-krds-primary-60"
            aria-label="검색"
            @click="isSearchOpen = true"
          >
            <Search class="h-5 w-5" aria-hidden="true" />
          </button>
          <button
            type="button"
            class="p-2 rounded-md hover:bg-krds-gray-5 focus:outline-none focus:ring-2 focus:ring-krds-primary-60 lg:hidden"
            :aria-label="isMobileMenuOpen ? '메뉴 닫기' : '메뉴 열기'"
            :aria-expanded="isMobileMenuOpen"
            @click="isMobileMenuOpen = !isMobileMenuOpen"
          >
            <X v-if="isMobileMenuOpen" class="h-5 w-5" aria-hidden="true" />
            <Menu v-else class="h-5 w-5" aria-hidden="true" />
          </button>
        </div>
      </Container>
    </div>

    <!-- Navigation -->
    <nav
      v-if="navigationItems && navigationItems.length > 0"
      id="gnb"
      :class="
        cn(
          'bg-white border-b border-krds-gray-10',
          'lg:block',
          isMobileMenuOpen ? 'block' : 'hidden'
        )
      "
      aria-label="주 메뉴"
    >
      <Container>
        <ul class="flex flex-col lg:flex-row lg:items-center lg:gap-2">
          <li
            v-for="(item, index) in navigationItems"
            :key="index"
            class="relative nav-item"
            @mouseenter="item.children && (openNavIndex = index)"
            @mouseleave="openNavIndex = null"
          >
            <!-- Has Children -->
            <template v-if="item.children && item.children.length > 0">
              <button
                type="button"
                :class="
                  cn(
                    'flex items-center gap-1 w-full lg:w-auto px-4 py-3 font-medium',
                    'hover:bg-krds-gray-5 rounded-md',
                    'focus:outline-none focus:ring-2 focus:ring-krds-primary-60',
                    item.active && 'text-krds-primary-60'
                  )
                "
                :aria-expanded="openNavIndex === index"
                @click="openNavIndex = openNavIndex === index ? null : index"
              >
                {{ item.label }}
                <ChevronDown
                  :class="
                    cn(
                      'h-4 w-4 transition-transform',
                      openNavIndex === index && 'rotate-180'
                    )
                  "
                  aria-hidden="true"
                />
              </button>
              <div
                v-if="openNavIndex === index"
                class="lg:absolute lg:top-full lg:left-0 lg:mt-1 lg:min-w-[200px] lg:rounded-md lg:border lg:border-krds-gray-20 lg:bg-white lg:shadow-lg bg-krds-gray-5 lg:bg-white"
              >
                <a
                  v-for="child in item.children"
                  :key="child.label"
                  :href="child.href"
                  :class="
                    cn(
                      'block px-4 py-2 text-sm',
                      'hover:bg-krds-gray-5',
                      'focus:outline-none focus:ring-2 focus:ring-krds-primary-60',
                      child.active && 'text-krds-primary-60 font-medium'
                    )
                  "
                  :aria-current="child.active ? 'page' : undefined"
                >
                  {{ child.label }}
                </a>
              </div>
            </template>

            <!-- Simple Link -->
            <a
              v-else
              :href="item.href"
              :class="
                cn(
                  'block px-4 py-3 font-medium',
                  'hover:bg-krds-gray-5 rounded-md',
                  'focus:outline-none focus:ring-2 focus:ring-krds-primary-60',
                  item.active && 'text-krds-primary-60'
                )
              "
              :aria-current="item.active ? 'page' : undefined"
            >
              {{ item.label }}
            </a>
          </li>
        </ul>
      </Container>
    </nav>

    <!-- Search Dialog -->
    <Teleport to="body">
      <div
        v-if="isSearchOpen"
        class="fixed inset-0 z-[100] bg-black/50"
        @click="isSearchOpen = false"
      />
      <div
        v-if="isSearchOpen"
        class="fixed top-0 left-0 right-0 z-[101] bg-white shadow-lg p-6"
      >
        <Container class="relative">
          <h2 class="text-lg font-bold mb-4">검색</h2>
          <div class="flex items-center gap-2">
            <Search class="h-5 w-5 text-krds-gray-40" aria-hidden="true" />
            <input
              v-model="searchQuery"
              type="search"
              placeholder="검색어를 입력하세요"
              class="flex-1 border-b border-krds-gray-30 py-2 text-lg focus:outline-none focus:border-krds-primary-60"
              @keydown.enter="handleSearch"
            />
          </div>
          <button
            type="button"
            class="absolute top-0 right-0 p-2 rounded-md hover:bg-krds-gray-5"
            aria-label="닫기"
            @click="isSearchOpen = false"
          >
            <X class="h-5 w-5" aria-hidden="true" />
          </button>
        </Container>
      </div>
    </Teleport>
  </header>
</template>

// packages/react/src/components/Header/Header.tsx
'use client';

import React from 'react';
import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
import * as Accordion from '@radix-ui/react-accordion';
import * as Dialog from '@radix-ui/react-dialog';
import styles from './header.module.scss';
import { ChevronDown, Search, Menu, X } from 'lucide-react';
import { Container } from '../container';

export interface HeaderProps {
  className?: string;
}

// 유틸리티 메뉴 데이터
const UTILITY_LINKS = [
  { label: '로그인', href: '#' },
  { label: '회원가입', href: '#' },
  { label: 'ENGLISH', href: '#' },
];

const RELATED_SITES = [
  { label: '건강iN', href: '#' },
  { label: 'The건강보험', href: '#' },
  { label: '요양기관업무포털', href: '#' },
  { label: '민원신청', href: '#' },
];

// 메인 메뉴 데이터
const MAIN_MENU = [
  {
    title: '건강보험',
    subItems: ['보험료', '급여', '요양기관', '건강검진'],
  },
  {
    title: '장기요양',
    subItems: ['장기요양보험', '장기요양인정', '장기요양기관', '장기요양급여'],
  },
  {
    title: '민원·증명서',
    subItems: ['민원신청', '증명서발급', '민원처리결과'],
  },
  {
    title: '건강정보',
    subItems: ['건강정보', '질병정보', '의학정보'],
  },
  {
    title: '건강IN',
    subItems: ['건강관리', '건강검진', '진료내역', '약제비'],
  },
  {
    title: '병원·약국',
    subItems: ['병원찾기', '약국찾기', '응급실찾기'],
  },
  {
    title: '소개',
    subItems: ['공단소개', '조직·업무', '채용정보', '알림·소식'],
  },
];

export function Header({ className }: HeaderProps) {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = React.useState(false);
  const [isUtilityDropdownOpen, setIsUtilityDropdownOpen] =
    React.useState(false);
  const [isSearchOpen, setIsSearchOpen] = React.useState(false);

  return (
    <header className={`${styles.header} ${className || ''}`}>
      {/* Header Utility */}
      <div className={styles.headerUtility}>
        <Container className={styles.inner}>
          <ul className={styles.utilityList}>
            {UTILITY_LINKS.map((link) => (
              <li key={link.label}>
                <button type="button" className={styles.utilityLink}>
                  {link.label}
                </button>
              </li>
            ))}
            <li>
              <DropdownMenu.Root
                open={isUtilityDropdownOpen}
                onOpenChange={setIsUtilityDropdownOpen}
                modal={false}
              >
                <DropdownMenu.Trigger asChild>
                  <button
                    type="button"
                    className={styles.utilityDropdownBtn}
                    aria-label="관련사이트 메뉴"
                    onMouseEnter={() => setIsUtilityDropdownOpen(true)}
                    onMouseLeave={() => setIsUtilityDropdownOpen(false)}
                  >
                    관련사이트
                    <ChevronDown className={styles.dropdownIcon} />
                  </button>
                </DropdownMenu.Trigger>

                <DropdownMenu.Portal>
                  <DropdownMenu.Content
                    className={styles.utilityDropdown}
                    sideOffset={5}
                    align="end"
                    onMouseEnter={() => setIsUtilityDropdownOpen(true)}
                    onMouseLeave={() => setIsUtilityDropdownOpen(false)}
                  >
                    {RELATED_SITES.map((site) => (
                      <DropdownMenu.Item key={site.label} asChild>
                        <a
                          href={site.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          title="새 창 열기"
                        >
                          {site.label}
                        </a>
                      </DropdownMenu.Item>
                    ))}
                  </DropdownMenu.Content>
                </DropdownMenu.Portal>
              </DropdownMenu.Root>
            </li>
          </ul>
        </Container>
      </div>

      {/* Header Branding */}
      <div className={styles.headerBranding}>
        <Container className={styles.inner}>
          <div className={styles.branding}>
            <a
              href="/"
              className={styles.logo}
              aria-label="대한민국정부 홈으로 이동"
            >
              <img
                src="https://www.krds.go.kr/resources/img/pattern/layout/head_logo.svg"
                alt="대한민국정부"
              />
            </a>
            <span className={styles.slogan}>
              <span className={styles.srOnly}>슬로건</span>
            </span>
          </div>

          {/* Header Actions */}
          <div className={styles.headerActions}>
            <Dialog.Root open={isSearchOpen} onOpenChange={setIsSearchOpen}>
              <Dialog.Trigger asChild>
                <button
                  type="button"
                  className={styles.searchBtn}
                  aria-label="검색"
                >
                  <Search />
                </button>
              </Dialog.Trigger>
              <Dialog.Portal>
                <Dialog.Overlay className={styles.searchOverlay} />
                <Dialog.Content className={styles.searchContent}>
                  <Dialog.Title className={styles.searchTitle}>
                    검색
                  </Dialog.Title>
                  <div className={styles.searchInputWrapper}>
                    <Search className={styles.searchIcon} aria-hidden="true" />
                    <input
                      type="search"
                      placeholder="검색어를 입력하세요"
                      className={styles.searchInput}
                      autoFocus
                    />
                  </div>
                  <Dialog.Close asChild>
                    <button
                      type="button"
                      className={styles.searchClose}
                      aria-label="닫기"
                    >
                      <X />
                    </button>
                  </Dialog.Close>
                </Dialog.Content>
              </Dialog.Portal>
            </Dialog.Root>
            <button
              type="button"
              className={styles.menuBtn}
              aria-label={isMobileMenuOpen ? '메뉴 닫기' : '메뉴 열기'}
              aria-expanded={isMobileMenuOpen}
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            >
              {isMobileMenuOpen ? <X /> : <Menu />}
            </button>
          </div>
        </Container>
      </div>

      {/* Header Main Menu */}
      <nav id="gnb" className={styles.mainMenu}>
        <ul className={styles.menuList}>
          {MAIN_MENU.map((menu) => (
            <li key={menu.title} className={styles.menuItem}>
              <a href="#" className={styles.menuLink}>
                {menu.title}
                {menu.subItems.length > 0 && (
                  <ChevronDown className={styles.menuIcon} aria-hidden="true" />
                )}
              </a>
              {/* Submenu */}
              {menu.subItems.length > 0 && (
                <div className={styles.subMenuWrapper}>
                  <div className={styles.subMenuInner}>
                    <ul className={styles.subMenuList}>
                      {menu.subItems.map((subItem) => (
                        <li key={subItem}>
                          <a href="#" className={styles.subMenuLink}>
                            {subItem}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}
            </li>
          ))}
        </ul>
      </nav>

      {/* Mobile Main Menu */}
      {isMobileMenuOpen && (
        <nav className={styles.mainMenuMobile} aria-label="모바일 메뉴">
          <div className={styles.mobileMenuHeader}>
            <button
              type="button"
              className={styles.mobileMenuCloseBtn}
              onClick={() => setIsMobileMenuOpen(false)}
              aria-label="메뉴 닫기"
            >
              <X />
            </button>
          </div>
          <div className={styles.mobileMenuInner}>
            <Accordion.Root type="multiple" className={styles.mobileMenuList}>
              {MAIN_MENU.map((menu) => (
                <Accordion.Item
                  key={menu.title}
                  value={menu.title}
                  className={styles.mobileMenuItem}
                >
                  <Accordion.Trigger className={styles.mobileMenuLink}>
                    {menu.title}
                    <ChevronDown
                      className={styles.mobileMenuIcon}
                      aria-hidden="true"
                    />
                  </Accordion.Trigger>
                  <Accordion.Content className={styles.mobileSubMenuList}>
                    <ul>
                      {menu.subItems.map((subItem) => (
                        <li key={subItem}>
                          <a href="#" className={styles.mobileSubMenuLink}>
                            {subItem}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </Accordion.Content>
                </Accordion.Item>
              ))}
            </Accordion.Root>

            {/* Mobile Utility */}
            <div className={styles.mobileUtility}>
              {UTILITY_LINKS.map((link) => (
                <button
                  key={link.label}
                  type="button"
                  className={styles.mobileUtilityBtn}
                >
                  {link.label}
                </button>
              ))}
            </div>
          </div>
        </nav>
      )}
    </header>
  );
}
