// packages/vue/src/components/Breadcrumb.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '../lib/utils';

export interface BreadcrumbItem {
  label: string;
  href?: string;
  isCurrent?: boolean;
}

const props = withDefaults(
  defineProps<{
    items: BreadcrumbItem[];
    separator?: string;
    maxItems?: number;
    itemsBeforeCollapse?: number;
    itemsAfterCollapse?: number;
    ariaLabel?: string;
    class?: string;
  }>(),
  {
    separator: '/',
    itemsBeforeCollapse: 1,
    itemsAfterCollapse: 1,
    ariaLabel: 'Breadcrumb',
  }
);

interface DisplayItem extends BreadcrumbItem {
  isCollapsed?: boolean;
}

const displayedItems = computed<DisplayItem[]>(() => {
  if (!props.maxItems || props.items.length <= props.maxItems) {
    return props.items;
  }

  const totalSlots = props.maxItems - 1;
  const before = props.itemsBeforeCollapse;
  const after = Math.max(1, totalSlots - before);

  const beforeItems = props.items.slice(0, before);
  const afterItems = props.items.slice(props.items.length - after);

  return [
    ...beforeItems,
    { label: '...', isCollapsed: true },
    ...afterItems,
  ];
});

const linkClasses = cn(
  'text-krds-gray-70',
  'hover:text-krds-gray-95',
  'transition-colors',
  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-krds-primary-base focus-visible:ring-offset-2',
  'rounded-sm'
);
</script>

<template>
  <nav
    id="breadcrumb"
    :aria-label="ariaLabel"
    :class="cn('pt-6 mb-10', props.class)"
  >
    <ol class="flex items-center flex-wrap gap-2">
      <li
        v-for="(item, index) in displayedItems"
        :key="item.href || `${item.label}-${index}`"
        class="flex items-center gap-2"
      >
        <!-- Collapsed indicator -->
        <span
          v-if="(item as DisplayItem).isCollapsed"
          class="text-krds-gray-60"
          aria-hidden="true"
        >
          {{ item.label }}
        </span>

        <!-- Current page -->
        <span
          v-else-if="item.isCurrent || index === displayedItems.length - 1"
          class="font-medium text-krds-gray-95"
          aria-current="page"
        >
          {{ item.label }}
        </span>

        <!-- Link -->
        <a
          v-else
          :href="item.href || '#'"
          :class="linkClasses"
        >
          {{ item.label }}
        </a>

        <!-- Separator -->
        <span
          v-if="index !== displayedItems.length - 1"
          class="text-krds-gray-50 select-none"
          aria-hidden="true"
        >
          {{ separator }}
        </span>
      </li>
    </ol>
  </nav>
</template>

// packages/react/src/components/Breadcrumb/Breadcrumb.tsx
'use client';

import * as React from 'react';
import { cn } from '../../lib/utils';

/**
 * Breadcrumb Props Interface
 */
export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  /**
   * Custom separator between items
   * @default ">"
   */
  separator?: React.ReactNode;

  /**
   * Additional className for nav element
   */
  className?: string;

  /**
   * Breadcrumb items
   */
  children: React.ReactNode;
}

/**
 * Breadcrumb Item Props Interface
 */
export interface BreadcrumbItemProps
  extends React.HTMLAttributes<HTMLLIElement> {
  /**
   * Link href (if not current page)
   */
  href?: string;

  /**
   * Whether this is the current page
   */
  current?: boolean;

  /**
   * Additional className
   */
  className?: string;

  /**
   * Item content
   */
  children: React.ReactNode;
}

/**
 * Breadcrumb Context
 */
interface BreadcrumbContextValue {
  separator: React.ReactNode;
}

const BreadcrumbContext = React.createContext<BreadcrumbContextValue>({
  separator: '>',
});

/**
 * Breadcrumb Component
 *
 * KRDS-compliant breadcrumb navigation with accessibility
 *
 * @example
 * ```tsx
 * <Breadcrumb>
 *   <BreadcrumbItem href="/">홈</BreadcrumbItem>
 *   <BreadcrumbItem href="/notice">공지사항</BreadcrumbItem>
 *   <BreadcrumbItem current>상세보기</BreadcrumbItem>
 * </Breadcrumb>
 * ```
 */
export const Breadcrumb = React.forwardRef<HTMLElement, BreadcrumbProps>(
  ({ separator = '>', className, children, ...props }, ref) => {
    return (
      <BreadcrumbContext.Provider value={{ separator }}>
        <nav
          ref={ref}
          aria-label="breadcrumb"
          className={cn('text-sm', className)}
          {...props}
        >
          <ol className="flex items-center flex-wrap gap-2">{children}</ol>
        </nav>
      </BreadcrumbContext.Provider>
    );
  }
);
Breadcrumb.displayName = 'Breadcrumb';

/**
 * Breadcrumb Item Component
 */
export const BreadcrumbItem = React.forwardRef<
  HTMLLIElement,
  BreadcrumbItemProps
>(({ href, current, className, children, ...props }, ref) => {
  const { separator } = React.useContext(BreadcrumbContext);
  const [isOverflowing, setIsOverflowing] = React.useState(false);
  const textRef = React.useRef<HTMLSpanElement>(null);

  React.useEffect(() => {
    const checkOverflow = () => {
      if (textRef.current) {
        setIsOverflowing(
          textRef.current.scrollWidth > textRef.current.clientWidth
        );
      }
    };

    checkOverflow();
    window.addEventListener('resize', checkOverflow);
    return () => window.removeEventListener('resize', checkOverflow);
  }, [children]);

  const content = (
    <span
      ref={textRef}
      className={cn(
        'max-w-[200px] truncate inline-block align-middle',
        isOverflowing && 'cursor-help'
      )}
      title={isOverflowing ? String(children) : undefined}
    >
      {children}
    </span>
  );

  return (
    <li
      ref={ref}
      className={cn('inline-flex items-center gap-2', className)}
      {...props}
    >
      {href && !current ? (
        <a
          href={href}
          className={cn(
            'text-gray-600 hover:text-[#256ef4] transition-colors',
            'focus:outline-none focus:ring-2 focus:ring-[#256ef4] rounded px-1'
          )}
        >
          {content}
        </a>
      ) : (
        <span
          className={cn(
            current
              ? 'text-gray-900 font-medium'
              : 'text-gray-600 cursor-default'
          )}
          aria-current={current ? 'page' : undefined}
        >
          {content}
        </span>
      )}

      {/* Separator - hide for last item */}
      <span
        className="text-gray-400 select-none last:hidden"
        aria-hidden="true"
      >
        {separator}
      </span>
    </li>
  );
});
BreadcrumbItem.displayName = 'BreadcrumbItem';
