// packages/vue/src/components/Input.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { cva } from 'class-variance-authority';
import { Eye, EyeOff, X } from 'lucide-vue-next';
import { cn } from '../lib/utils';

const inputVariants = cva(
  'flex w-full rounded-md font-bold transition-colors placeholder:text-krds-gray-40 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-60 disabled:bg-krds-gray-10 read-only:bg-krds-gray-5 read-only:cursor-default',
  {
    variants: {
      variant: {
        default:
          'border border-krds-gray-60 bg-krds-white focus-visible:border-2 focus-visible:border-krds-primary-base',
        filled:
          'border border-transparent bg-krds-gray-10 focus-visible:border-2 focus-visible:border-krds-primary-base',
      },
      size: {
        sm: 'h-10 px-4 text-[15px] rounded-md leading-[150%]',
        md: 'h-12 px-4 text-[17px] rounded-md leading-[150%]',
        lg: 'h-14 px-4 text-[19px] rounded-lg leading-[150%]',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  }
);

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    type?: string;
    variant?: 'default' | 'filled';
    size?: 'sm' | 'md' | 'lg';
    status?: 'error' | 'success' | 'info';
    disabled?: boolean;
    readonly?: boolean;
    clearable?: boolean;
    placeholder?: string;
    class?: string;
  }>(),
  {
    type: 'text',
    variant: 'default',
    size: 'md',
    disabled: false,
    readonly: false,
    clearable: false,
  }
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
  clear: [];
}>();

const showPassword = ref(false);
const inputRef = ref<HTMLInputElement | null>(null);

const inputType = computed(() => {
  if (props.type === 'password' && showPassword.value) {
    return 'text';
  }
  return props.type;
});

const hasValue = computed(() => !!props.modelValue);

const hasError = computed(() => props.status === 'error');

const statusClasses = computed(() => {
  if (hasError.value) {
    return 'border-krds-danger-60 focus-visible:border-2 focus-visible:border-krds-danger-60';
  }
  return '';
});

const inputClasses = computed(() =>
  cn(
    inputVariants({ variant: props.variant, size: props.size }),
    statusClasses.value,
    ($slots.leftAddon || props.type === 'password' || props.clearable) && 'pr-10',
    $slots.leftAddon && 'pl-10'
  )
);

const wrapperClasses = computed(() => cn('relative flex items-center', props.class));

const handleInput = (e: Event) => {
  const target = e.target as HTMLInputElement;
  emit('update:modelValue', target.value);
};

const handleClear = () => {
  emit('update:modelValue', '');
  emit('clear');
  inputRef.value?.focus();
};

const togglePassword = () => {
  showPassword.value = !showPassword.value;
};

// $slots를 정의
const $slots = defineSlots<{
  leftAddon?: () => any;
  rightAddon?: () => any;
}>();

const hasLeftAddon = computed(() => !!$slots.leftAddon);
const hasRightAddon = computed(() => !!$slots.rightAddon || props.type === 'password' || (props.clearable && hasValue.value));
</script>

<template>
  <div :class="wrapperClasses">
    <div
      v-if="hasLeftAddon"
      class="pointer-events-none absolute left-3 flex items-center text-krds-gray-60"
    >
      <slot name="leftAddon" />
    </div>
    <input
      ref="inputRef"
      :type="inputType"
      :value="modelValue"
      :disabled="disabled"
      :readonly="readonly"
      :placeholder="placeholder"
      :class="inputClasses"
      :aria-invalid="hasError ? true : undefined"
      @input="handleInput"
    />
    <div
      v-if="hasRightAddon"
      class="absolute right-3 flex items-center gap-2 text-krds-gray-60"
    >
      <button
        v-if="clearable && hasValue"
        type="button"
        class="cursor-pointer hover:text-krds-primary-60 transition-colors"
        aria-label="입력 지우기"
        tabindex="-1"
        @click="handleClear"
      >
        <X :size="16" />
      </button>
      <button
        v-if="type === 'password'"
        type="button"
        class="cursor-pointer hover:text-krds-primary-60 transition-colors"
        :aria-label="showPassword ? '비밀번호 숨기기' : '비밀번호 보기'"
        tabindex="-1"
        @click="togglePassword"
      >
        <EyeOff v-if="showPassword" :size="20" />
        <Eye v-else :size="20" />
      </button>
      <slot name="rightAddon" />
    </div>
  </div>
</template>

// packages/react/src/components/Input/Input.tsx
import { cva, type VariantProps } from 'class-variance-authority';
import * as React from 'react';
import { cn } from '../../lib/utils';

/**
 * Input Variants Definition
 *
 * Uses class-variance-authority (cva) for type-safe variant management
 */
const inputVariants = cva(
  [
    'flex',
    'w-full',
    'rounded-md',
    'font-medium',
    'transition-colors',
    'placeholder:text-gray-400',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-offset-2',
    'disabled:cursor-not-allowed',
    'disabled:opacity-60',
    'disabled:bg-gray-100',
  ].join(' '),
  {
    variants: {
      /**
       * Variant - Visual style
       */
      variant: {
        default: [
          'border',
          'border-gray-300',
          'bg-white',
          'focus-visible:ring-[#256ef4]',
        ].join(' '),
        filled: [
          'border-0',
          'bg-gray-100',
          'focus-visible:ring-[#256ef4]',
        ].join(' '),
      },
      /**
       * Size - Height and padding
       */
      size: {
        sm: ['h-8', 'px-3', 'text-sm'].join(' '), // 32px
        md: ['h-10', 'px-4', 'text-base'].join(' '), // 40px - default
        lg: ['h-12', 'px-4', 'text-lg'].join(' '), // 48px
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  }
);

/**
 * Input Props Interface
 */
export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>,
    VariantProps<typeof inputVariants> {
  /**
   * Input size
   * @default "md"
   */
  size?: 'sm' | 'md' | 'lg';

  /**
   * Input variant (visual style)
   * @default "default"
   */
  variant?: 'default' | 'filled';

  /**
   * Error state
   * Shows error styling and sets aria-invalid
   */
  error?: boolean;

  /**
   * Left addon element (icon, prefix, etc.)
   */
  leftAddon?: React.ReactNode;

  /**
   * Right addon element (icon, suffix, etc.)
   */
  rightAddon?: React.ReactNode;

  /**
   * Additional className for layout adjustments
   *
   * ⚠️ Warning: Props take precedence over className
   * - Allowed: margin, width, max-width
   * - Ignored: height, padding, border (use size/variant props)
   */
  className?: string;
}

/**
 * Input Component
 *
 * KRDS-compliant input component with:
 * - Props-based API (size, variant)
 * - Full accessibility support
 * - Error state handling
 * - Addon support (left/right)
 * - className escape hatch for layout
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Input placeholder="이름 입력" />
 *
 * // With variants
 * <Input variant="default" />
 * <Input variant="filled" />
 *
 * // With sizes
 * <Input size="small" />
 * <Input size="large" />
 *
 * // With error
 * <Input error />
 *
 * // With addons
 * <Input leftAddon={<SearchIcon />} placeholder="검색" />
 * <Input rightAddon={<CheckIcon />} />
 *
 * // With layout className
 * <Input className="w-full max-w-md" />
 *
 * // Form integration
 * <label htmlFor="email">이메일</label>
 * <Input
 *   id="email"
 *   type="email"
 *   placeholder="example@email.com"
 *   aria-describedby="email-error"
 * />
 * ```
 */
export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  (
    {
      className,
      type = 'text',
      variant,
      size,
      error = false,
      disabled = false,
      leftAddon,
      rightAddon,
      ...props
    },
    ref
  ) => {
    // If there are addons, wrap in container
    if (leftAddon || rightAddon) {
      return (
        <div className={cn('relative flex items-center', className)}>
          {leftAddon && (
            <div className="pointer-events-none absolute left-3 flex items-center text-gray-500">
              {leftAddon}
            </div>
          )}
          <input
            type={type}
            className={cn(
              inputVariants({ variant, size }),
              error &&
                'border-[#DC3545] focus-visible:ring-[#DC3545] focus-visible:ring-offset-0',
              leftAddon && 'pl-10',
              rightAddon && 'pr-10'
            )}
            ref={ref}
            disabled={disabled}
            aria-invalid={error}
            {...props}
          />
          {rightAddon && (
            <div className="pointer-events-none absolute right-3 flex items-center text-gray-500">
              {rightAddon}
            </div>
          )}
        </div>
      );
    }

    // Simple input without addons
    return (
      <input
        type={type}
        className={cn(
          inputVariants({ variant, size }),
          error &&
            'border-[#DC3545] focus-visible:ring-[#DC3545] focus-visible:ring-offset-0',
          className
        )}
        ref={ref}
        disabled={disabled}
        aria-invalid={error}
        {...props}
      />
    );
  }
);

Input.displayName = 'Input';

/**
 * Export inputVariants for extending
 */
export { inputVariants };
