// packages/vue/src/components/HeaderWithNavigation.vue
<script setup lang="ts">
/**
 * HeaderWithNavigation 컴포넌트
 * NavigationMenu를 포함하는 헤더 컴포넌트
 */
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { Search, Menu, X } from 'lucide-vue-next';
import { cn } from '@/lib/utils';
import Container from './Container.vue';
import Button from './Button.vue';
import Logo from './Logo.vue';
import NavigationMenu from './NavigationMenu.vue';
import SearchModal from './SearchModal.vue';

// ============================================================================
// Types
// ============================================================================

export interface NavigationMenuLink {
  label: string;
  href: string;
  description?: string;
  active?: boolean;
}

export interface NavigationMenuSection {
  title?: string;
  links: NavigationMenuLink[];
  utilityLinks?: NavigationMenuLink[];
}

export interface NavigationMenuItem {
  label: string;
  href?: string;
  active?: boolean;
  sections?: NavigationMenuSection[];
  children?: NavigationMenuLink[];
  dropdownWidth?: string;
}

// ============================================================================
// Props
// ============================================================================

const props = withDefaults(
  defineProps<{
    /** NavigationMenu 항목 데이터 */
    menuItems: NavigationMenuItem[];
    /** 현재 경로 */
    currentPath?: string;
    /** 로고 이미지 URL */
    logo?: string;
    /** 로고 alt 텍스트 */
    logoAlt?: string;
    /** 로고 링크 */
    logoHref?: string;
    /** 스크롤 시 헤더 동작 */
    stickyBehavior?: 'always' | 'auto' | 'never';
    /** auto 모드에서 헤더가 사라지기 시작하는 스크롤 위치 */
    scrollThreshold?: number;
    /** 인기검색어 목록 */
    popularKeywords?: any[];
    /** 최근검색어 목록 */
    recentKeywords?: any[];
    /** 추가 className */
    class?: string;
  }>(),
  {
    logo: 'https://www.krds.go.kr/resources/img/pattern/layout/head_logo.svg',
    logoAlt: '대한민국정부',
    logoHref: '/',
    stickyBehavior: 'always',
    scrollThreshold: 150,
    popularKeywords: () => [],
    recentKeywords: () => [],
  }
);

const emit = defineEmits<{
  (e: 'search', value: string): void;
}>();

// ============================================================================
// State
// ============================================================================

const isMobileMenuOpen = ref(false);
const isSearchOpen = ref(false);
const isScrolled = ref(false);

// ============================================================================
// Computed
// ============================================================================

const positionClass = computed(() =>
  props.stickyBehavior === 'never' ? 'relative' : 'sticky top-0'
);

const hideClass = computed(() =>
  props.stickyBehavior === 'auto' && isScrolled.value ? '-translate-y-full' : ''
);

// ============================================================================
// Effects
// ============================================================================

function handleScroll() {
  isScrolled.value = window.scrollY > props.scrollThreshold;
}

onMounted(() => {
  if (props.stickyBehavior === 'auto') {
    handleScroll();
    window.addEventListener('scroll', handleScroll, { passive: true });
  }
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});

// ============================================================================
// Handlers
// ============================================================================

function handleSearch(value: string) {
  emit('search', value);
  isSearchOpen.value = false;
}
</script>

<template>
  <header
    :class="cn(
      'relative left-0 z-[70] bg-white border-b border-krds-gray-20 transition-transform duration-500 ease-in-out',
      positionClass,
      hideClass,
      props.class
    )"
  >
    <!-- Branding + NavigationMenu + Actions -->
    <Container class="flex items-center justify-between py-2 gap-4">
      <!-- Logo -->
      <Logo :src="logo" :alt="logoAlt" :href="logoHref">
        <template #slogan>
          <slot name="slogan" />
        </template>
      </Logo>

      <!-- NavigationMenu - Inline -->
      <NavigationMenu
        :items="menuItems"
        :current-path="currentPath"
        class="hidden lg:block flex-1"
      />

      <!-- Actions -->
      <div class="inline-flex gap-3 md:gap-0">
        <Button
          variant="ghost"
          size="icon"
          class="min-w-0 hover:bg-krds-gray-10"
          aria-label="검색"
          @click="isSearchOpen = true"
        >
          <Search class="w-6 h-6" aria-hidden="true" />
        </Button>
        <SearchModal
          v-model:open="isSearchOpen"
          :popular-keywords="popularKeywords"
          :recent-keywords="recentKeywords"
          @search="handleSearch"
        />
        <Button
          variant="ghost"
          size="icon"
          class="lg:hidden min-w-0 hover:bg-krds-gray-10"
          :aria-label="isMobileMenuOpen ? '메뉴 닫기' : '메뉴 열기'"
          :aria-expanded="isMobileMenuOpen"
          @click="isMobileMenuOpen = !isMobileMenuOpen"
        >
          <X v-if="isMobileMenuOpen" class="w-6 h-6" aria-hidden="true" />
          <Menu v-else class="w-6 h-6" aria-hidden="true" />
        </Button>
      </div>
    </Container>

    <!-- Mobile Menu -->
    <Teleport to="body">
      <div
        v-if="isMobileMenuOpen"
        class="lg:hidden fixed inset-0 z-[1000] bg-white overflow-y-auto"
      >
        <div class="flex justify-end items-center p-5 border-b border-krds-gray-20 sticky top-0 bg-white z-10">
          <Button
            variant="ghost"
            size="icon"
            class="min-w-0 hover:bg-krds-gray-10"
            aria-label="메뉴 닫기"
            @click="isMobileMenuOpen = false"
          >
            <X class="w-6 h-6" aria-hidden="true" />
          </Button>
        </div>
        <div class="p-5">
          <ul class="list-none m-0 p-0">
            <li
              v-for="(item, index) in menuItems"
              :key="`${item.label}-${index}`"
              class="border-b border-krds-gray-20 last:border-b-0"
            >
              <a
                v-if="item.href && !item.sections && !item.children"
                :href="item.href"
                class="block py-4 text-base font-bold text-krds-gray-90 hover:text-krds-primary-60 transition-colors"
              >
                {{ item.label }}
              </a>
              <template v-else>
                <div class="py-4 text-base font-bold text-krds-gray-90">
                  {{ item.label }}
                </div>
                <ul
                  v-if="item.children"
                  class="list-none m-0 p-0 pb-3 pl-4"
                >
                  <li v-for="child in item.children" :key="child.label">
                    <a
                      :href="child.href"
                      class="block py-2 text-krds-body-sm font-medium text-krds-gray-90 hover:text-krds-primary-60 transition-colors"
                    >
                      {{ child.label }}
                    </a>
                  </li>
                </ul>
                <template v-if="item.sections">
                  <ul
                    v-for="(section, sIndex) in item.sections"
                    :key="sIndex"
                    class="list-none m-0 p-0 pb-3 pl-4"
                  >
                    <li v-for="link in section.links" :key="link.label">
                      <a
                        :href="link.href"
                        class="block py-2 text-krds-body-sm font-medium text-krds-gray-90 hover:text-krds-primary-60 transition-colors"
                      >
                        {{ link.label }}
                      </a>
                    </li>
                  </ul>
                </template>
              </template>
            </li>
          </ul>
        </div>
      </div>
    </Teleport>
  </header>
</template>

// packages/react/src/components/header-with-navigation.tsx
'use client';

import React from 'react';
import { Search, Menu, X, SquareArrowOutUpRight } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Container } from './container';
import { Button } from './button';
import { Logo } from './logo';
import { NavigationMenu, NavigationMenuItem } from './menu-navigation';
import {
  SearchModal,
  SAMPLE_POPULAR_KEYWORDS,
  SAMPLE_RECENT_KEYWORDS,
} from './search-modal';
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from './dropdown-menu';

// Re-export for convenience
export type { NavigationMenuItem } from './menu-navigation';

/**
 * Utility Link 타입
 * - href만 있으면 일반 링크
 * - children이 있으면 DropdownMenu로 렌더링
 */
export interface UtilityLink {
  label: string;
  href?: string;
  children?: UtilityLink[];
  /** 외부 링크 여부 (새 창에서 열기) */
  external?: boolean;
}

export interface HeaderWithNavigationTailwindProps {
  className?: string;
  navigationItems: NavigationMenuItem[];
  utilityLinks?: UtilityLink[];
  logo?: string;
  logoAlt?: string;
  logoHref?: string;
  slogan?: React.ReactNode;
  /**
   * 스크롤 시 헤더 동작
   * - 'always': 항상 sticky (기본값)
   * - 'auto': 스크롤 시 헤더가 위로 사라짐 (KRDS 스타일)
   * - 'never': 항상 relative (스크롤과 함께 이동)
   */
  stickyBehavior?: 'always' | 'auto' | 'never';
  /** auto 모드에서 헤더가 사라지기 시작하는 스크롤 위치 (px) */
  scrollThreshold?: number;
}

const DEFAULT_UTILITY_LINKS: UtilityLink[] = [
  { label: '로그인', href: '#' },
  { label: '회원가입', href: '#' },
  { label: 'ENGLISH', href: '#' },
  {
    label: '관련사이트',
    children: [
      { label: '건강iN', href: '#', external: true },
      { label: 'The건강보험', href: '#', external: true },
      { label: '요양기관업무포털', href: '#', external: true },
      { label: '민원신청', href: '#', external: true },
    ],
  },
];

/**
 * Header with NavigationMenu (Tailwind CSS version)
 *
 * Stacked layout:
 * - Line 1: logo | actions
 * - Line 2: NavigationMenu (full width)
 */
export function HeaderWithNavigationTailwind({
  className,
  navigationItems,
  utilityLinks = DEFAULT_UTILITY_LINKS,
  logo = 'https://www.krds.go.kr/resources/img/pattern/layout/head_logo.svg',
  logoAlt = '대한민국정부',
  logoHref = '/',
  slogan,
  stickyBehavior = 'always',
  scrollThreshold = 150,
}: HeaderWithNavigationTailwindProps) {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = React.useState(false);
  const [isSearchOpen, setIsSearchOpen] = React.useState(false);
  const [isScrolled, setIsScrolled] = React.useState(false);

  // 스크롤 감지 (auto 모드에서만 동작)
  React.useEffect(() => {
    if (stickyBehavior !== 'auto') return;

    const handleScroll = () => {
      setIsScrolled(window.scrollY > scrollThreshold);
    };

    // 초기 상태 설정
    handleScroll();

    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, [stickyBehavior, scrollThreshold]);

  // position 클래스 결정
  const positionClass =
    stickyBehavior === 'never' ? 'relative' : 'sticky top-0';

  // auto 모드에서 스크롤 시 헤더 숨기기 (transform 사용)
  const hideClass =
    stickyBehavior === 'auto' && isScrolled ? '-translate-y-full' : '';

  return (
    <header
      className={cn(
        'left-0 z-[70] bg-white border-b border-krds-gray-20 transition-transform duration-500 ease-in-out',
        positionClass,
        hideClass,
        className
      )}
    >
      {/* Utility Bar */}
      {utilityLinks && utilityLinks.length > 0 && (
        <div className="hidden lg:flex justify-end">
          <Container className="flex justify-end">
            <ul className="flex justify-end list-none m-0 p-0">
              {utilityLinks.map((link, index) => (
                <li key={link.label} className="relative flex items-center">
                  {index !== 0 && (
                    <span className="inline-flex w-px h-3 bg-krds-gray-20" />
                  )}
                  {link.children && link.children.length > 0 ? (
                    // Depth 2: DropdownMenu
                    <DropdownMenu>
                      <DropdownMenuTrigger className="inline-flex items-center gap-1 text-krds-body-sm font-medium text-krds-gray-90 hover:text-krds-primary-60 transition-colors py-2 px-3">
                        {link.label}
                      </DropdownMenuTrigger>
                      <DropdownMenuContent
                        className="rounded-xl min-w-[140px] py-2.5 z-[100]"
                        sideOffset={5}
                        align="end"
                      >
                        {link.children.map((child) => (
                          <a
                            key={child.label}
                            href={child.href}
                            {...(child.external && {
                              target: '_blank',
                              rel: 'noopener noreferrer',
                            })}
                          >
                            <DropdownMenuItem className="flex items-center gap-1 text-krds-body-sm">
                              {child.label}
                              {child.external && (
                                <SquareArrowOutUpRight
                                  className="w-3 h-3"
                                  aria-hidden="true"
                                />
                              )}
                            </DropdownMenuItem>
                          </a>
                        ))}
                      </DropdownMenuContent>
                    </DropdownMenu>
                  ) : (
                    // Depth 1: 일반 링크
                    <a
                      href={link.href}
                      className="inline-flex items-center text-krds-body-sm font-medium text-krds-gray-90 hover:text-krds-primary-60 transition-colors py-2 px-3"
                      {...(link.external && {
                        target: '_blank',
                        rel: 'noopener noreferrer',
                      })}
                    >
                      {link.label}
                      {link.external && (
                        <SquareArrowOutUpRight
                          className="w-3 h-3 ml-1"
                          aria-hidden="true"
                        />
                      )}
                    </a>
                  )}
                </li>
              ))}
            </ul>
          </Container>
        </div>
      )}

      {/* Branding + Actions (Line 1) */}
      <Container className="flex items-center justify-between py-5 lg:py-6 gap-2">
        {/* Logo */}
        <Logo src={logo} alt={logoAlt} href={logoHref} slogan={slogan} />

        {/* Actions */}
        <div className="inline-flex gap-3 md:gap-0">
          <Button
            variant="ghost"
            size="icon"
            className="min-w-0 hover:bg-krds-gray-10"
            aria-label="검색"
            onClick={() => setIsSearchOpen(true)}
          >
            <Search className="w-6 h-6" aria-hidden="true" />
          </Button>
          <SearchModal
            open={isSearchOpen}
            onOpenChange={setIsSearchOpen}
            popularKeywords={SAMPLE_POPULAR_KEYWORDS}
            recentKeywords={SAMPLE_RECENT_KEYWORDS}
            onSearch={(value) => {
              console.log('검색:', value);
              setIsSearchOpen(false);
            }}
          />
          <Button
            variant="ghost"
            size="icon"
            className="lg:hidden min-w-0 hover:bg-krds-gray-10"
            aria-label={isMobileMenuOpen ? '메뉴 닫기' : '메뉴 열기'}
            aria-expanded={isMobileMenuOpen}
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          >
            {isMobileMenuOpen ? (
              <X className="w-6 h-6" aria-hidden="true" />
            ) : (
              <Menu className="w-6 h-6" aria-hidden="true" />
            )}
          </Button>
        </div>
      </Container>

      {/* NavigationMenu (Line 2) - Desktop only */}
      <nav
        id="gnb"
        className="hidden lg:flex justify-center w-full bg-white border-t border-krds-gray-20"
        aria-label="주 메뉴"
      >
        <Container>
          <NavigationMenu items={navigationItems} />
        </Container>
      </nav>

      {/* Mobile Menu */}
      {isMobileMenuOpen && (
        <div className="lg:hidden fixed inset-0 z-[1000] bg-white overflow-y-auto">
          <div className="flex justify-end items-center p-5 border-b border-krds-gray-20 sticky top-0 bg-white z-10">
            <Button
              variant="ghost"
              size="icon"
              className="min-w-0 hover:bg-krds-gray-10"
              onClick={() => setIsMobileMenuOpen(false)}
              aria-label="메뉴 닫기"
            >
              <X className="w-6 h-6" aria-hidden="true" />
            </Button>
          </div>
          <div className="p-5">
            <ul className="list-none m-0 p-0">
              {navigationItems.map((item) => (
                <li
                  key={item.label}
                  className="border-b border-krds-gray-20 last:border-b-0"
                >
                  <a
                    href={item.href}
                    className="flex items-center justify-between w-full py-4 text-krds-body-lg font-bold text-krds-gray-90 hover:text-krds-primary-60 transition-colors"
                  >
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
            {utilityLinks && utilityLinks.length > 0 && (
              <div className="flex flex-col gap-3 mt-8 pt-5 border-t border-krds-gray-20">
                {utilityLinks
                  .filter((link) => !link.children)
                  .map((link) => (
                    <Button
                      key={link.label}
                      href={link.href}
                      variant="tertiary"
                      className="w-full justify-center"
                    >
                      {link.label}
                    </Button>
                  ))}
              </div>
            )}
          </div>
        </div>
      )}
    </header>
  );
}

export { HeaderWithNavigationTailwind as HeaderWithNavigation };
