// packages/vue/src/components/Radio.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { cva } from 'class-variance-authority';
import { Circle } from 'lucide-vue-next';
import { cn } from '../lib/utils';

const radioVariants = cva(
  'aspect-square rounded-full border border-krds-gray-60 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-krds-primary-base focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-60 transition-colors',
  {
    variants: {
      size: {
        sm: 'h-4 w-4',
        md: 'h-5 w-5',
        lg: 'h-6 w-6',
      },
    },
    defaultVariants: {
      size: 'md',
    },
  }
);

// RadioGroup Context
interface RadioGroupContext {
  modelValue: string | undefined;
  size: 'sm' | 'md' | 'lg';
  status?: 'error' | 'success' | 'info';
  disabled: boolean;
  updateValue: (value: string) => void;
}

const radioGroupKey = Symbol('radioGroup');

const props = withDefaults(
  defineProps<{
    value: string;
    label?: string;
    size?: 'sm' | 'md' | 'lg';
    status?: 'error' | 'success' | 'info';
    disabled?: boolean;
    class?: string;
  }>(),
  {
    size: 'md',
    disabled: false,
  }
);

const group = inject<RadioGroupContext | null>(radioGroupKey, null);

const isChecked = computed(() => group?.modelValue === props.value);
const finalSize = computed(() => group?.size || props.size);
const finalStatus = computed(() => group?.status || props.status);
const finalDisabled = computed(() => group?.disabled || props.disabled);
const hasError = computed(() => finalStatus.value === 'error');

const radioClasses = computed(() => {
  const base = radioVariants({ size: finalSize.value });
  const checkedClasses = isChecked.value
    ? 'border-krds-primary-base text-krds-primary-base'
    : '';
  const errorClasses = hasError.value
    ? 'border-krds-danger-60 data-[state=checked]:border-krds-danger-60 data-[state=checked]:text-krds-danger-60'
    : '';
  return cn(base, checkedClasses, errorClasses);
});

const indicatorSize = computed(() => {
  switch (finalSize.value) {
    case 'sm':
      return 8;
    case 'lg':
      return 12;
    default:
      return 10;
  }
});

const labelClasses = computed(() =>
  cn(
    'text-krds-body-md text-krds-gray-90 cursor-pointer select-none',
    finalDisabled.value && 'cursor-not-allowed opacity-60'
  )
);

const handleClick = () => {
  if (!finalDisabled.value && group) {
    group.updateValue(props.value);
  }
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === ' ' || e.key === 'Enter') {
    e.preventDefault();
    handleClick();
  }
};
</script>

<template>
  <div :class="cn('flex items-center gap-2', props.class)">
    <button
      type="button"
      role="radio"
      :aria-checked="isChecked"
      :disabled="finalDisabled"
      :class="radioClasses"
      :data-state="isChecked ? 'checked' : 'unchecked'"
      @click="handleClick"
      @keydown="handleKeyDown"
    >
      <span v-if="isChecked" class="flex items-center justify-center">
        <Circle :size="indicatorSize" class="fill-current" :stroke-width="0" />
      </span>
    </button>
    <span v-if="label" :class="labelClasses" @click="handleClick">{{ label }}</span>
  </div>
</template>

// packages/react/src/components/radio.tsx
'use client';

import * as React from 'react';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
import { Circle } from 'lucide-react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@/lib/utils';
import { useFormFieldOptional } from './form-field';

const radioVariants = cva(
  [
    'aspect-square',
    'rounded-full',
    'border',
    'border-krds-gray-60',
    'ring-offset-background',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-krds-primary-base',
    'focus-visible:ring-offset-2',
    'disabled:cursor-not-allowed',
    'disabled:opacity-60',
    'data-[state=checked]:border-krds-primary-base',
    'data-[state=checked]:text-krds-primary-base',
    'transition-colors',
  ].join(' '),
  {
    variants: {
      size: {
        sm: 'h-4 w-4', // 16px
        md: 'h-5 w-5', // 20px
        lg: 'h-6 w-6', // 24px
      },
    },
    defaultVariants: {
      size: 'md',
    },
  }
);

export interface RadioGroupProps
  extends Omit<
      React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root>,
      'size'
    >,
    VariantProps<typeof radioVariants> {
  size?: 'sm' | 'md' | 'lg';
  status?: 'error' | 'success' | 'info';
  error?: boolean; // @deprecated status="error" 사용 권장
}

export const RadioGroup = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Root>,
  RadioGroupProps
>(
  (
    {
      className,
      size = 'md',
      status,
      error = false,
      disabled,
      orientation = 'horizontal',
      ...props
    },
    ref
  ) => {
    // FormField 컨텍스트 (선택적)
    const formField = useFormFieldOptional();

    const finalStatus =
      status || formField?.status || (error ? 'error' : undefined);
    const finalDisabled = formField?.disabled || disabled;

    return (
      <RadioGroupContext.Provider value={{ size, status: finalStatus }}>
        <RadioGroupPrimitive.Root
          className={cn(
            'flex',
            orientation === 'vertical' ? 'flex-col gap-3' : 'flex-row gap-4',
            className
          )}
          disabled={finalDisabled}
          orientation={orientation}
          aria-invalid={finalStatus === 'error' ? true : undefined}
          aria-describedby={
            [formField?.errorId, formField?.helperId]
              .filter(Boolean)
              .join(' ') || undefined
          }
          {...props}
          ref={ref}
        />
      </RadioGroupContext.Provider>
    );
  }
);

RadioGroup.displayName = RadioGroupPrimitive.Root.displayName;

// RadioGroup Context
interface RadioGroupContextValue {
  size?: 'sm' | 'md' | 'lg';
  status?: 'error' | 'success' | 'info';
}

const RadioGroupContext = React.createContext<RadioGroupContextValue>({});

const useRadioGroupContext = () => {
  return React.useContext(RadioGroupContext);
};

export interface RadioGroupItemProps
  extends Omit<
    React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Item>,
    'size'
  > {
  size?: 'sm' | 'md' | 'lg';
  status?: 'error' | 'success' | 'info';
}

export const RadioGroupItem = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Item>,
  RadioGroupItemProps
>(({ className, size: sizeProp, status: statusProp, ...props }, ref) => {
  const context = useRadioGroupContext();
  const size = sizeProp || context.size || 'md';
  const status = statusProp || context.status;
  const hasError = status === 'error';

  const getStatusClasses = () => {
    if (hasError) {
      return 'border-krds-danger-60 data-[state=checked]:border-krds-danger-60 data-[state=checked]:text-krds-danger-60';
    }
    return '';
  };

  const getIndicatorSize = () => {
    switch (size) {
      case 'sm':
        return 8;
      case 'lg':
        return 12;
      case 'md':
      default:
        return 10;
    }
  };

  return (
    <RadioGroupPrimitive.Item
      ref={ref}
      className={cn(radioVariants({ size }), getStatusClasses(), className)}
      {...props}
    >
      <RadioGroupPrimitive.Indicator className="flex items-center justify-center">
        <Circle
          size={getIndicatorSize()}
          className="fill-current"
          strokeWidth={0}
        />
      </RadioGroupPrimitive.Indicator>
    </RadioGroupPrimitive.Item>
  );
});

RadioGroupItem.displayName = RadioGroupPrimitive.Item.displayName;

// Radio - 라벨이 포함된 편의 컴포넌트
export interface RadioProps {
  value: string;
  label: React.ReactNode;
  disabled?: boolean;
  className?: string;
}

export const Radio = React.forwardRef<HTMLDivElement, RadioProps>(
  ({ value, label, disabled, className }, ref) => {
    const context = useRadioGroupContext();
    const size = context.size || 'md';

    const getLabelSize = () => {
      switch (size) {
        case 'sm':
          return 'text-krds-body-sm';
        case 'lg':
          return 'text-krds-body-lg';
        case 'md':
        default:
          return 'text-krds-body-md';
      }
    };

    return (
      <div ref={ref} className={cn('flex items-center gap-2', className)}>
        <RadioGroupItem value={value} id={value} disabled={disabled} />
        <label
          htmlFor={value}
          className={cn(
            getLabelSize(),
            'text-krds-gray-90 cursor-pointer select-none',
            disabled && 'cursor-not-allowed opacity-60'
          )}
        >
          {label}
        </label>
      </div>
    );
  }
);

Radio.displayName = 'Radio';

export { radioVariants };
