// packages/vue/src/components/Slider.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { cva } from 'class-variance-authority';
import { cn } from '../lib/utils';

const sliderVariants = cva(
  'relative flex w-full touch-none select-none items-center',
  {
    variants: {
      size: {
        sm: '',
        md: '',
        lg: '',
      },
    },
    defaultVariants: {
      size: 'md',
    },
  }
);

const trackSizes = {
  sm: 'h-1',
  md: 'h-1.5',
  lg: 'h-2',
};

const thumbSizes = {
  sm: 'h-3 w-3',
  md: 'h-4 w-4',
  lg: 'h-5 w-5',
};

const colorClasses = {
  primary: {
    range: 'bg-krds-primary-base',
    thumb: 'border-krds-primary-base focus-visible:ring-krds-primary-base',
  },
  secondary: {
    range: 'bg-krds-gray-60',
    thumb: 'border-krds-gray-60 focus-visible:ring-krds-gray-60',
  },
  success: {
    range: 'bg-krds-func-success-base',
    thumb: 'border-krds-func-success-base focus-visible:ring-krds-func-success-base',
  },
  danger: {
    range: 'bg-krds-danger-base',
    thumb: 'border-krds-danger-base focus-visible:ring-krds-danger-base',
  },
};

type SliderColor = 'primary' | 'secondary' | 'success' | 'danger';

const props = withDefaults(
  defineProps<{
    modelValue?: number | number[];
    min?: number;
    max?: number;
    step?: number;
    size?: 'sm' | 'md' | 'lg';
    color?: SliderColor;
    showValue?: boolean;
    formatValue?: (value: number) => string;
    disabled?: boolean;
    label?: string;
    labelId?: string;
    class?: string;
  }>(),
  {
    min: 0,
    max: 100,
    step: 1,
    size: 'md',
    color: 'primary',
    showValue: false,
    formatValue: (v: number) => String(v),
    disabled: false,
  }
);

const emit = defineEmits<{
  'update:modelValue': [value: number | number[]];
}>();

const internalValue = ref<number[]>(
  Array.isArray(props.modelValue)
    ? props.modelValue
    : [props.modelValue ?? props.min]
);

watch(
  () => props.modelValue,
  (newValue) => {
    if (newValue !== undefined) {
      internalValue.value = Array.isArray(newValue) ? newValue : [newValue];
    }
  }
);

const isRange = computed(() => internalValue.value.length > 1);

const percentage = computed(() => {
  const range = props.max - props.min;
  if (isRange.value) {
    const start = ((internalValue.value[0] - props.min) / range) * 100;
    const end = ((internalValue.value[1] - props.min) / range) * 100;
    return { start, end };
  }
  return { start: 0, end: ((internalValue.value[0] - props.min) / range) * 100 };
});

const rangeStyle = computed(() => ({
  left: `${percentage.value.start}%`,
  width: `${percentage.value.end - percentage.value.start}%`,
}));

const thumbPosition = computed(() => {
  const range = props.max - props.min;
  return internalValue.value.map((v) => ((v - props.min) / range) * 100);
});

const handleThumbDrag = (index: number, event: MouseEvent | TouchEvent) => {
  if (props.disabled) return;

  const track = (event.currentTarget as HTMLElement).parentElement;
  if (!track) return;

  const rect = track.getBoundingClientRect();

  const updateValue = (clientX: number) => {
    const percent = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    const value = Math.round((percent * (props.max - props.min) + props.min) / props.step) * props.step;

    const newValues = [...internalValue.value];
    newValues[index] = Math.max(props.min, Math.min(props.max, value));

    // 범위 슬라이더: 값 정렬
    if (isRange.value) {
      if (index === 0 && newValues[0] > newValues[1]) {
        newValues[0] = newValues[1];
      } else if (index === 1 && newValues[1] < newValues[0]) {
        newValues[1] = newValues[0];
      }
    }

    internalValue.value = newValues;
    emit('update:modelValue', isRange.value ? newValues : newValues[0]);
  };

  const handleMove = (e: MouseEvent | TouchEvent) => {
    const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX;
    updateValue(clientX);
  };

  const handleEnd = () => {
    document.removeEventListener('mousemove', handleMove);
    document.removeEventListener('mouseup', handleEnd);
    document.removeEventListener('touchmove', handleMove);
    document.removeEventListener('touchend', handleEnd);
  };

  document.addEventListener('mousemove', handleMove);
  document.addEventListener('mouseup', handleEnd);
  document.addEventListener('touchmove', handleMove);
  document.addEventListener('touchend', handleEnd);
};

const handleTrackClick = (event: MouseEvent) => {
  if (props.disabled) return;

  const track = event.currentTarget as HTMLElement;
  const rect = track.getBoundingClientRect();
  const percent = (event.clientX - rect.left) / rect.width;
  const value = Math.round((percent * (props.max - props.min) + props.min) / props.step) * props.step;
  const clampedValue = Math.max(props.min, Math.min(props.max, value));

  if (isRange.value) {
    // 가장 가까운 thumb으로 이동
    const distToFirst = Math.abs(clampedValue - internalValue.value[0]);
    const distToSecond = Math.abs(clampedValue - internalValue.value[1]);
    const newValues = [...internalValue.value];
    if (distToFirst < distToSecond) {
      newValues[0] = clampedValue;
    } else {
      newValues[1] = clampedValue;
    }
    internalValue.value = newValues;
    emit('update:modelValue', newValues);
  } else {
    internalValue.value = [clampedValue];
    emit('update:modelValue', clampedValue);
  }
};

const classes = computed(() => cn(sliderVariants({ size: props.size }), props.class));
</script>

<template>
  <div class="w-full">
    <!-- Label and value display -->
    <div v-if="label || showValue" class="mb-2 flex items-center justify-between">
      <label
        v-if="label"
        :id="labelId"
        class="text-sm font-medium text-krds-gray-70"
      >
        {{ label }}
      </label>
      <span v-if="showValue" class="text-sm text-krds-gray-50">
        <template v-if="isRange">
          {{ formatValue(internalValue[0]) }} - {{ formatValue(internalValue[internalValue.length - 1]) }}
        </template>
        <template v-else>
          {{ formatValue(internalValue[0]) }}
        </template>
      </span>
    </div>

    <!-- Slider -->
    <div
      :class="classes"
      role="slider"
      :aria-valuemin="min"
      :aria-valuemax="max"
      :aria-valuenow="isRange ? undefined : internalValue[0]"
      :aria-disabled="disabled"
      :aria-labelledby="labelId"
    >
      <!-- Track -->
      <div
        :class="cn(
          'relative grow overflow-hidden rounded-full bg-krds-gray-20',
          trackSizes[size]
        )"
        @click="handleTrackClick"
      >
        <!-- Range -->
        <div
          :class="cn('absolute h-full', colorClasses[color].range)"
          :style="rangeStyle"
        />
      </div>

      <!-- Thumbs -->
      <div
        v-for="(_, index) in internalValue"
        :key="index"
        :class="cn(
          'absolute block rounded-full border-2 bg-white shadow-md transition-colors',
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2',
          'cursor-pointer',
          disabled && 'pointer-events-none opacity-50',
          thumbSizes[size],
          colorClasses[color].thumb
        )"
        :style="{ left: `calc(${thumbPosition[index]}% - ${size === 'sm' ? '6px' : size === 'lg' ? '10px' : '8px'})` }"
        tabindex="0"
        @mousedown="handleThumbDrag(index, $event)"
        @touchstart="handleThumbDrag(index, $event)"
      />
    </div>
  </div>
</template>

// packages/react/src/components/slider.tsx
'use client';

import * as React from 'react';
import * as SliderPrimitive from '@radix-ui/react-slider';
import { cn } from '@/lib/utils';
import { cva, type VariantProps } from 'class-variance-authority';

// ============================================================================
// Slider Variants
// ============================================================================

const sliderVariants = cva(
  'relative flex w-full touch-none select-none items-center',
  {
    variants: {
      size: {
        sm: '[&_[data-slider-track]]:h-1 [&_[data-slider-thumb]]:h-3 [&_[data-slider-thumb]]:w-3',
        md: '[&_[data-slider-track]]:h-1.5 [&_[data-slider-thumb]]:h-4 [&_[data-slider-thumb]]:w-4',
        lg: '[&_[data-slider-track]]:h-2 [&_[data-slider-thumb]]:h-5 [&_[data-slider-thumb]]:w-5',
      },
    },
    defaultVariants: {
      size: 'md',
    },
  }
);

const sliderTrackVariants = cva(
  'relative grow overflow-hidden rounded-full bg-krds-gray-20',
  {
    variants: {
      color: {
        primary: '',
        secondary: '',
        success: '',
        danger: '',
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  }
);

const sliderRangeVariants = cva('absolute h-full', {
  variants: {
    color: {
      primary: 'bg-krds-primary-base',
      secondary: 'bg-krds-gray-60',
      success: 'bg-krds-func-success-base',
      danger: 'bg-krds-danger-base',
    },
  },
  defaultVariants: {
    color: 'primary',
  },
});

const sliderThumbVariants = cva(
  [
    'block rounded-full border-2 bg-white shadow-md transition-colors',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2',
    'disabled:pointer-events-none disabled:opacity-50',
  ],
  {
    variants: {
      color: {
        primary:
          'border-krds-primary-base focus-visible:ring-krds-primary-base',
        secondary: 'border-krds-gray-60 focus-visible:ring-krds-gray-60',
        success:
          'border-krds-func-success-base focus-visible:ring-krds-func-success-base',
        danger: 'border-krds-danger-base focus-visible:ring-krds-danger-base',
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  }
);

// ============================================================================
// Slider Color Type
// ============================================================================

type SliderColor = 'primary' | 'secondary' | 'success' | 'danger';

// ============================================================================
// Slider Props
// ============================================================================

export interface SliderProps
  extends Omit<
      React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root>,
      'value' | 'defaultValue' | 'onValueChange' | 'color'
    >,
    VariantProps<typeof sliderVariants> {
  /** 색상 */
  color?: SliderColor;
  /** 현재 값 (단일 값 또는 범위) */
  value?: number | number[];
  /** 기본 값 */
  defaultValue?: number | number[];
  /** 값 변경 콜백 */
  onValueChange?: (value: number | number[]) => void;
  /** 최소값 */
  min?: number;
  /** 최대값 */
  max?: number;
  /** 증가 단위 */
  step?: number;
  /** 값 표시 여부 */
  showValue?: boolean;
  /** 값 포맷터 */
  formatValue?: (value: number) => string;
  /** 비활성화 */
  disabled?: boolean;
  /** 라벨 */
  label?: string;
  /** 라벨 ID (접근성) */
  labelId?: string;
}

// ============================================================================
// Slider Component
// ============================================================================

const Slider = React.forwardRef<
  React.ElementRef<typeof SliderPrimitive.Root>,
  SliderProps
>(
  (
    {
      className,
      size,
      color,
      value,
      defaultValue,
      onValueChange,
      min = 0,
      max = 100,
      step = 1,
      showValue = false,
      formatValue = (v) => String(v),
      disabled = false,
      label,
      labelId,
      ...props
    },
    ref
  ) => {
    // 단일 값을 배열로 정규화
    const normalizedValue = React.useMemo(() => {
      if (value === undefined) return undefined;
      return Array.isArray(value) ? value : [value];
    }, [value]);

    const normalizedDefaultValue = React.useMemo(() => {
      if (defaultValue === undefined) return [min];
      return Array.isArray(defaultValue) ? defaultValue : [defaultValue];
    }, [defaultValue, min]);

    // 값 변경 핸들러
    const handleValueChange = React.useCallback(
      (newValue: number[]) => {
        if (onValueChange) {
          // 원래 형식에 맞게 반환
          if (
            Array.isArray(value) ||
            Array.isArray(defaultValue) ||
            newValue.length > 1
          ) {
            onValueChange(newValue);
          } else {
            onValueChange(newValue[0]);
          }
        }
      },
      [onValueChange, value, defaultValue]
    );

    const isRange =
      (normalizedValue && normalizedValue.length > 1) ||
      (normalizedDefaultValue && normalizedDefaultValue.length > 1);
    const currentValue = normalizedValue || normalizedDefaultValue || [min];

    return (
      <div className="w-full">
        {/* 라벨 및 값 표시 */}
        {(label || showValue) && (
          <div className="mb-2 flex items-center justify-between">
            {label && (
              <label
                id={labelId}
                className="text-sm font-medium text-krds-gray-70"
              >
                {label}
              </label>
            )}
            {showValue && (
              <span className="text-sm text-krds-gray-50">
                {isRange
                  ? `${formatValue(currentValue[0])} - ${formatValue(currentValue[currentValue.length - 1])}`
                  : formatValue(currentValue[0])}
              </span>
            )}
          </div>
        )}

        {/* 슬라이더 */}
        <SliderPrimitive.Root
          ref={ref}
          className={cn(sliderVariants({ size }), className)}
          value={normalizedValue}
          defaultValue={normalizedDefaultValue}
          onValueChange={handleValueChange}
          min={min}
          max={max}
          step={step}
          disabled={disabled}
          aria-labelledby={labelId}
          {...props}
        >
          <SliderPrimitive.Track
            data-slider-track
            className={cn(sliderTrackVariants({ color: color ?? 'primary' }))}
          >
            <SliderPrimitive.Range
              className={cn(sliderRangeVariants({ color: color ?? 'primary' }))}
            />
          </SliderPrimitive.Track>
          {currentValue.map((_, index) => (
            <SliderPrimitive.Thumb
              key={index}
              data-slider-thumb
              className={cn(sliderThumbVariants({ color: color ?? 'primary' }))}
            />
          ))}
        </SliderPrimitive.Root>
      </div>
    );
  }
);

Slider.displayName = 'Slider';

// ============================================================================
// Exports
// ============================================================================

export { Slider, sliderVariants };
