// packages/vue/src/components/SkipLink.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { cn } from '../lib/utils';

export interface SkipLinkItem {
  href: string;
  label: string;
}

const props = withDefaults(
  defineProps<{
    links?: SkipLinkItem[];
    variant?: 'visible' | 'hidden';
    class?: string;
  }>(),
  {
    links: () => [{ href: '#main-content', label: '본문 바로가기' }],
    variant: 'hidden',
  }
);

onMounted(() => {
  if (import.meta.env.DEV && props.links.length > 3) {
    console.warn(
      'SkipLink: 최대 3개 링크를 권장합니다. 현재 개수:',
      props.links.length
    );
  }
});

const handleClick = (e: MouseEvent, href: string) => {
  e.preventDefault();

  const targetId = href.replace('#', '');
  const targetElement = document.getElementById(targetId);

  if (targetElement) {
    targetElement.scrollIntoView({
      behavior: 'smooth',
      block: 'start',
    });

    const firstFocusable = targetElement.querySelector(
      'button:not([disabled]), [href]:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'
    ) as HTMLElement;

    setTimeout(() => {
      if (firstFocusable) {
        firstFocusable.focus();
      } else {
        targetElement.setAttribute('tabindex', '-1');
        targetElement.focus();
      }
    }, 100);

    if (window.history.pushState) {
      window.history.pushState(null, '', href);
    } else {
      window.location.hash = href;
    }
  }
};

const hiddenLinkClass =
  'fixed left-0 -top-full z-[9999] w-full h-8 px-4 py-2 text-[15px] text-center ' +
  'bg-krds-gray-90 text-white ' +
  'focus:top-0 focus:outline-none focus:ring-2 focus:ring-krds-func-info focus:ring-offset-2';

const visibleLinkClass =
  'block w-full px-4 py-2 text-sm text-center ' +
  'bg-krds-gray-90 text-white ' +
  'hover:bg-krds-gray-80 ' +
  'focus:outline-none focus:ring-2 focus:ring-krds-func-info focus:ring-offset-2';

const navClasses = computed(() =>
  cn(props.variant === 'visible' && 'flex flex-col', props.class)
);
</script>

<template>
  <nav
    id="krds-skip-link"
    aria-label="건너뛰기 링크"
    :class="navClasses"
  >
    <a
      v-for="link in links"
      :key="link.href"
      :href="link.href"
      @click="handleClick($event, link.href)"
      :class="variant === 'visible' ? visibleLinkClass : hiddenLinkClass"
    >
      {{ link.label }}
    </a>
  </nav>
</template>

// packages/react/src/components/SkipLink/SkipLink.tsx
'use client';

import * as React from 'react';
import { cn } from '../../lib/utils';

/**
 * SkipLink Variant Types
 */
export type SkipLinkVariant = 'visible' | 'hidden';

/**
 * SkipLink Link Item
 */
export interface SkipLinkItem {
  /**
   * Link destination (href)
   */
  href: string;

  /**
   * Link label text
   */
  label: string;
}

/**
 * SkipLink Props
 */
export interface SkipLinkProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Array of skip link items (max 3 recommended)
   */
  links: SkipLinkItem[];

  /**
   * Visual variant
   * @default "hidden"
   */
  variant?: SkipLinkVariant;

  /**
   * Additional CSS classes
   */
  className?: string;
}

/**
 * SkipLink Component (건너뛰기 링크)
 *
 * **Foundation Layer Features:**
 * - ✅ Required CSS ID: #krds-skip-link (KRDS mandatory)
 * - ✅ Keyboard Navigation: Tab and Enter keys
 * - ✅ WCAG 2.1 / KWCAG 2.2 Compliance: Bypass Blocks (Level A), Focus Visible (Level AA)
 * - ✅ Focus Management: Automatic scroll to destination
 * - ✅ Screen Reader Support: Semantic navigation landmarks
 *
 * **KRDS Standards:**
 * - Allows keyboard and screen reader users to bypass repetitive content
 * - Must be the first element in page (except after cookie banners/modals)
 * - Maximum 3 links recommended
 * - Two variants: visible (always shown) and hidden (shows on focus)
 * - Focus must scroll to destination and be visually distinct
 * - Links must be keyboard accessible (Tab and Enter)
 *
 * **Structure:**
 * - Container: #krds-skip-link navigation element
 * - Links: Anchor elements with focus indicators
 *
 * @example
 * ```tsx
 * // Basic usage (hidden variant)
 * <SkipLink
 *   links={[
 *     { href: '#main-content', label: '본문 바로가기' },
 *     { href: '#main-navigation', label: '주 메뉴 바로가기' },
 *   ]}
 * />
 *
 * // Visible variant
 * <SkipLink
 *   variant="visible"
 *   links={[
 *     { href: '#main-content', label: '본문 바로가기' },
 *     { href: '#main-navigation', label: '주 메뉴 바로가기' },
 *     { href: '#footer', label: '하단 메뉴 바로가기' },
 *   ]}
 * />
 *
 * // Recommended page structure
 * <body>
 *   <SkipLink links={[{ href: '#main-content', label: '본문 바로가기' }]} />
 *   <Masthead />
 *   <header>...</header>
 *   <main id="main-content" tabIndex={-1}>...</main>
 *   <footer>...</footer>
 * </body>
 * ```
 */
export const SkipLink = React.forwardRef<HTMLDivElement, SkipLinkProps>(
  ({ links, variant = 'hidden', className, ...props }, ref) => {
    // Validate max 3 links
    React.useEffect(() => {
      if (links.length > 3) {
        console.warn(
          'SkipLink: Maximum 3 links recommended for optimal accessibility. Current count:',
          links.length
        );
      }
    }, [links]);

    const handleClick = (
      e: React.MouseEvent<HTMLAnchorElement>,
      href: string
    ) => {
      e.preventDefault();

      // Find target element
      const targetId = href.replace('#', '');
      const targetElement = document.getElementById(targetId);

      if (targetElement) {
        // Set focus on target element
        targetElement.setAttribute('tabindex', '-1');
        targetElement.focus();

        // Scroll to target element
        targetElement.scrollIntoView({
          behavior: 'smooth',
          block: 'start',
        });

        // Update URL hash without triggering scroll
        if (window.history.pushState) {
          window.history.pushState(null, '', href);
        } else {
          window.location.hash = href;
        }
      }
    };

    const variantStyles = {
      visible: 'relative',
      hidden: 'absolute -top-full left-0 focus-within:top-0',
    };

    return (
      <nav
        ref={ref}
        id="krds-skip-link"
        aria-label="Skip navigation"
        className={cn(
          'w-full',
          'bg-blue-600',
          'z-50',
          variantStyles[variant],
          className
        )}
        {...props}
      >
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <ul className="flex items-center gap-4 min-h-[48px] py-2">
            {links.map((link, index) => (
              <li key={`${link.href}-${index}`}>
                <a
                  href={link.href}
                  onClick={(e) => handleClick(e, link.href)}
                  className={cn(
                    'inline-block',
                    'px-4 py-2',
                    'text-sm font-medium',
                    'text-white',
                    'bg-blue-700',
                    'rounded',
                    'transition-colors',
                    'hover:bg-blue-800',
                    'focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-blue-600',
                    variant === 'hidden' &&
                      'focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-blue-600'
                  )}
                >
                  {link.label}
                </a>
              </li>
            ))}
          </ul>
        </div>
      </nav>
    );
  }
);

SkipLink.displayName = 'SkipLink';
