// apps/docs/src/app/kits/vue/board/page.tsx
'use client';

import {
  PageSection as Section,
  Heading,
  Subsection,
  PageNavigation,
} from '@/components/content';
import { CodeBlock } from '@/components/content/CodeBlock';
import {
  Code,
  Badge,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Table,
  TableHead,
  TableHeader,
  TableBody,
  TableRow,
  TableCell,
  List,
  ListItem,
  Alert,
} from '@hanui/react';

// 타입 정의 (React와 동일)
const typeCode = `// src/features/board/types/board.ts

// 게시글 타입 (DummyJSON 응답 형식)
export interface Post {
  id: number
  title: string
  body: string
  tags: string[]
  reactions: { likes: number; dislikes: number }
  views: number
  userId: number
}

// 게시글 목록 응답
export interface PostListResponse {
  posts: Post[]
  total: number
  skip: number
  limit: number
}

// 게시글 작성/수정 폼 데이터
export interface PostFormData {
  title: string
  body: string
  userId: number
  tags?: string[]
}

// 목록 조회 파라미터
export interface PostListParams {
  skip?: number
  limit?: number
  search?: string
}`;

// API 코드 (React와 동일)
const apiCode = `// src/features/board/api/boardApi.ts
import axios from 'axios'
import type { Post, PostListResponse, PostFormData, PostListParams } from '../types/board'

const API_URL = 'https://dummyjson.com'

const api = axios.create({
  baseURL: API_URL,
  headers: { 'Content-Type': 'application/json' },
})

// 게시글 목록 조회
export async function getPosts(params?: PostListParams): Promise<PostListResponse> {
  if (params?.search) {
    const { data } = await api.get('/posts/search', {
      params: { q: params.search, limit: params.limit, skip: params.skip }
    })
    return data
  }
  const { data } = await api.get('/posts', {
    params: { limit: params?.limit || 10, skip: params?.skip || 0 }
  })
  return data
}

// 게시글 상세 조회
export async function getPost(id: number): Promise<Post> {
  const { data } = await api.get(\`/posts/\${id}\`)
  return data
}

// 게시글 작성
export async function createPost(formData: PostFormData): Promise<Post> {
  const { data } = await api.post('/posts/add', formData)
  return data
}

// 게시글 수정
export async function updatePost(id: number, formData: PostFormData): Promise<Post> {
  const { data } = await api.put(\`/posts/\${id}\`, formData)
  return data
}

// 게시글 삭제
export async function deletePost(id: number): Promise<Post & { isDeleted: boolean }> {
  const { data } = await api.delete(\`/posts/\${id}\`)
  return data
}`;

// Pinia Store
const storeCode = `// src/features/board/stores/boardStore.ts
import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useBoardStore = defineStore('board', () => {
  // State
  const searchKeyword = ref('')
  const sortBy = ref<'latest' | 'views'>('latest')
  const skip = ref(0)
  const limit = ref(10)
  const selectedIds = ref<number[]>([])
  const isDeleteModalOpen = ref(false)
  const deleteTargetId = ref<number | null>(null)

  // Getters
  const currentPage = computed(() => Math.floor(skip.value / limit.value) + 1)
  const hasSelection = computed(() => selectedIds.value.length > 0)

  // Actions
  function setSearchKeyword(keyword: string) {
    searchKeyword.value = keyword
    skip.value = 0
  }

  function setSortBy(sort: 'latest' | 'views') {
    sortBy.value = sort
    skip.value = 0
  }

  function nextPage() {
    skip.value += limit.value
  }

  function prevPage() {
    skip.value = Math.max(0, skip.value - limit.value)
  }

  function toggleSelect(id: number) {
    const index = selectedIds.value.indexOf(id)
    if (index > -1) {
      selectedIds.value.splice(index, 1)
    } else {
      selectedIds.value.push(id)
    }
  }

  function selectAll(ids: number[]) {
    selectedIds.value = ids
  }

  function clearSelection() {
    selectedIds.value = []
  }

  function openDeleteModal(id: number) {
    deleteTargetId.value = id
    isDeleteModalOpen.value = true
  }

  function closeDeleteModal() {
    deleteTargetId.value = null
    isDeleteModalOpen.value = false
  }

  function resetFilters() {
    searchKeyword.value = ''
    sortBy.value = 'latest'
    skip.value = 0
    clearSelection()
  }

  return {
    // State
    searchKeyword,
    sortBy,
    skip,
    limit,
    selectedIds,
    isDeleteModalOpen,
    deleteTargetId,
    // Getters
    currentPage,
    hasSelection,
    // Actions
    setSearchKeyword,
    setSortBy,
    nextPage,
    prevPage,
    toggleSelect,
    selectAll,
    clearSelection,
    openDeleteModal,
    closeDeleteModal,
    resetFilters,
  }
})`;

// Vue Query Composables
const composablesCode = `// src/features/board/composables/useBoard.ts
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query'
import { computed, type Ref } from 'vue'
import { useBoardStore } from '../stores/boardStore'
import { getPosts, getPost, createPost, updatePost, deletePost } from '../api/boardApi'
import type { PostFormData } from '../types/board'

// Query Keys
export const boardKeys = {
  all: ['board'] as const,
  lists: () => [...boardKeys.all, 'list'] as const,
  list: (params: object) => [...boardKeys.lists(), params] as const,
  details: () => [...boardKeys.all, 'detail'] as const,
  detail: (id: number) => [...boardKeys.details(), id] as const,
}

// 게시글 목록 조회
export function usePosts() {
  const store = useBoardStore()

  // 반응형 파라미터 - store 값이 변경되면 자동으로 쿼리 재실행
  const params = computed(() => ({
    skip: store.skip,
    limit: store.limit,
    search: store.searchKeyword || undefined,
  }))

  return useQuery({
    queryKey: computed(() => boardKeys.list(params.value)),
    queryFn: () => getPosts(params.value),
  })
}

// 게시글 상세 조회
export function usePost(id: Ref<number> | number) {
  const postId = computed(() => typeof id === 'number' ? id : id.value)

  return useQuery({
    queryKey: computed(() => boardKeys.detail(postId.value)),
    queryFn: () => getPost(postId.value),
    enabled: computed(() => postId.value > 0),
  })
}

// 게시글 작성
export function useCreatePost() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: PostFormData) => createPost(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: boardKeys.lists() })
    },
  })
}

// 게시글 수정
export function useUpdatePost() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: PostFormData }) =>
      updatePost(id, data),
    onSuccess: (_, { id }) => {
      queryClient.invalidateQueries({ queryKey: boardKeys.lists() })
      queryClient.invalidateQueries({ queryKey: boardKeys.detail(id) })
    },
  })
}

// 게시글 삭제
export function useDeletePost() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (id: number) => deletePost(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: boardKeys.lists() })
    },
  })
}`;

// 게시글 목록 컴포넌트
const boardListComponent = `<!-- src/views/board/BoardListView.vue -->
<script setup lang="ts">
import { useBoardStore } from '@/features/board/stores/boardStore'
import { usePosts } from '@/features/board/composables/useBoard'
import PostCard from '@/components/board/PostCard.vue'
import Pagination from '@/components/common/Pagination.vue'

const store = useBoardStore()
const { data, isLoading, error } = usePosts()
</script>

<template>
  <div class="max-w-4xl mx-auto p-4">
    <!-- 헤더 -->
    <div class="flex justify-between items-center mb-6">
      <h1 class="text-2xl font-bold">게시판</h1>
      <RouterLink to="/board/write" class="btn btn-primary">
        글쓰기
      </RouterLink>
    </div>

    <!-- 검색 -->
    <div class="mb-4">
      <input
        type="text"
        :value="store.searchKeyword"
        @input="store.setSearchKeyword(($event.target as HTMLInputElement).value)"
        placeholder="검색어를 입력하세요..."
        class="w-full p-3 border rounded-lg"
      />
    </div>

    <!-- 로딩 상태 -->
    <div v-if="isLoading" class="flex justify-center py-12">
      <div class="animate-spin w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full" />
    </div>

    <!-- 에러 상태 -->
    <div v-else-if="error" class="text-center py-12 text-red-500">
      데이터를 불러오는데 실패했습니다.
    </div>

    <!-- 게시글 목록 -->
    <template v-else>
      <div class="space-y-4">
        <PostCard
          v-for="post in data?.posts"
          :key="post.id"
          :post="post"
          :selected="store.selectedIds.includes(post.id)"
          @toggle-select="store.toggleSelect(post.id)"
        />
      </div>

      <!-- 페이지네이션 -->
      <Pagination
        :current-page="store.currentPage"
        :total="data?.total || 0"
        :limit="store.limit"
        @prev="store.prevPage"
        @next="store.nextPage"
        class="mt-6"
      />
    </template>
  </div>
</template>`;

// 게시글 카드 컴포넌트
const postCardComponent = `<!-- src/components/board/PostCard.vue -->
<script setup lang="ts">
import type { Post } from '@/features/board/types/board'

interface Props {
  post: Post
  selected?: boolean
}

defineProps<Props>()
defineEmits<{
  toggleSelect: []
}>()
</script>

<template>
  <article
    class="p-4 border rounded-lg hover:shadow-md transition-shadow"
    :class="{ 'border-blue-500 bg-blue-50': selected }"
  >
    <div class="flex items-start gap-3">
      <!-- 체크박스 -->
      <input
        type="checkbox"
        :checked="selected"
        @change="$emit('toggleSelect')"
        class="mt-1"
      />

      <div class="flex-1">
        <!-- 제목 -->
        <RouterLink
          :to="\`/board/\${post.id}\`"
          class="text-lg font-semibold hover:text-blue-600"
        >
          {{ post.title }}
        </RouterLink>

        <!-- 본문 미리보기 -->
        <p class="text-gray-600 mt-1 line-clamp-2">
          {{ post.body }}
        </p>

        <!-- 태그 -->
        <div class="flex gap-2 mt-2">
          <span
            v-for="tag in post.tags"
            :key="tag"
            class="px-2 py-0.5 bg-gray-100 text-gray-600 text-xs rounded"
          >
            #{{ tag }}
          </span>
        </div>

        <!-- 메타 정보 -->
        <div class="flex gap-4 mt-3 text-sm text-gray-500">
          <span class="flex items-center gap-1">
            <span>👁</span> {{ post.views }}
          </span>
          <span class="flex items-center gap-1">
            <span>👍</span> {{ post.reactions.likes }}
          </span>
          <span class="flex items-center gap-1">
            <span>👎</span> {{ post.reactions.dislikes }}
          </span>
        </div>
      </div>
    </div>
  </article>
</template>`;

// 게시글 상세 컴포넌트
const postDetailComponent = `<!-- src/views/board/BoardDetailView.vue -->
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { usePost, useDeletePost } from '@/features/board/composables/useBoard'

const route = useRoute()
const router = useRouter()

const postId = computed(() => Number(route.params.id))
const { data: post, isLoading, error } = usePost(postId)

const deletePost = useDeletePost()
const showDeleteConfirm = ref(false)

async function handleDelete() {
  await deletePost.mutateAsync(postId.value)
  router.push('/board')
}
</script>

<template>
  <div class="max-w-4xl mx-auto p-4">
    <!-- 로딩 -->
    <div v-if="isLoading" class="text-center py-12">
      로딩 중...
    </div>

    <!-- 에러 -->
    <div v-else-if="error" class="text-center py-12 text-red-500">
      게시글을 찾을 수 없습니다.
    </div>

    <!-- 게시글 상세 -->
    <article v-else-if="post">
      <header class="border-b pb-4 mb-4">
        <h1 class="text-2xl font-bold mb-2">{{ post.title }}</h1>
        <div class="flex gap-4 text-sm text-gray-500">
          <span>조회 {{ post.views }}</span>
          <span>좋아요 {{ post.reactions.likes }}</span>
        </div>
      </header>

      <div class="prose max-w-none mb-8">
        {{ post.body }}
      </div>

      <!-- 태그 -->
      <div class="flex gap-2 mb-8">
        <span
          v-for="tag in post.tags"
          :key="tag"
          class="px-3 py-1 bg-gray-100 rounded-full text-sm"
        >
          #{{ tag }}
        </span>
      </div>

      <!-- 액션 버튼 -->
      <div class="flex gap-2">
        <RouterLink :to="\`/board/\${post.id}/edit\`" class="btn">
          수정
        </RouterLink>
        <button @click="showDeleteConfirm = true" class="btn btn-danger">
          삭제
        </button>
        <RouterLink to="/board" class="btn btn-outline">
          목록
        </RouterLink>
      </div>
    </article>

    <!-- 삭제 확인 모달 -->
    <Teleport to="body">
      <div v-if="showDeleteConfirm" class="fixed inset-0 bg-black/50 flex items-center justify-center">
        <div class="bg-white p-6 rounded-lg max-w-md">
          <h2 class="text-lg font-bold mb-4">삭제 확인</h2>
          <p class="mb-6">정말 이 게시글을 삭제하시겠습니까?</p>
          <div class="flex gap-2 justify-end">
            <button @click="showDeleteConfirm = false" class="btn">
              취소
            </button>
            <button
              @click="handleDelete"
              :disabled="deletePost.isPending.value"
              class="btn btn-danger"
            >
              {{ deletePost.isPending.value ? '삭제 중...' : '삭제' }}
            </button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>`;

// 파일 구조
const fileStructure = [
  { path: 'types/board.ts', desc: '타입 정의' },
  { path: 'api/boardApi.ts', desc: 'API 함수 (DummyJSON)' },
  { path: 'stores/boardStore.ts', desc: 'Pinia 스토어' },
  { path: 'composables/useBoard.ts', desc: 'Vue Query 훅' },
];

export default function VueBoardKitPage() {
  return (
    <>
      <Heading
        level="h1"
        title="Board Kit (Vue)"
        description="Vue 3 + Composition API로 구현한 게시판 기능 키트"
      />

      <div className="flex gap-2 mb-6">
        <Badge variant="primary">Vue 3</Badge>
        <Badge variant="secondary">Pinia</Badge>
        <Badge variant="secondary">Vue Query</Badge>
        <Badge variant="outline-gray">DummyJSON</Badge>
      </div>

      <Alert variant="info" className="mb-6">
        API 코드는 React 버전과 동일합니다. Pinia와 Vue Query로 상태관리만
        변환됩니다.
      </Alert>

      <Section level="h2">
        <Heading level="h2" id="file-structure" title="파일 구조" />
        <CodeBlock
          code={`src/features/board/
├── types/
│   └── board.ts          # 타입 정의
├── api/
│   └── boardApi.ts       # API 함수 (DummyJSON)
├── stores/
│   └── boardStore.ts     # Pinia 스토어 (UI 상태)
└── composables/
    └── useBoard.ts       # Vue Query 훅 (서버 상태)`}
          language="plaintext"
        />
      </Section>

      <Tabs defaultValue="types" className="w-full mt-8">
        <TabsList>
          <TabsTrigger value="types">타입</TabsTrigger>
          <TabsTrigger value="api">API</TabsTrigger>
          <TabsTrigger value="store">Store</TabsTrigger>
          <TabsTrigger value="composables">Composables</TabsTrigger>
          <TabsTrigger value="components">컴포넌트</TabsTrigger>
        </TabsList>

        <TabsContent value="types">
          <Section level="h2">
            <Heading level="h2" id="types" title="타입 정의" />
            <p className="text-krds-gray-70 mt-4 mb-4">
              타입 정의는 React 버전과 동일합니다.
            </p>
            <CodeBlock code={typeCode} language="typescript" />
          </Section>
        </TabsContent>

        <TabsContent value="api">
          <Section level="h2">
            <Heading level="h2" id="api" title="API 코드" />
            <p className="text-krds-gray-70 mt-4 mb-4">
              API 코드도 React 버전과 동일합니다. DummyJSON <Code>/posts</Code>{' '}
              엔드포인트를 사용합니다.
            </p>
            <CodeBlock code={apiCode} language="typescript" />
          </Section>
        </TabsContent>

        <TabsContent value="store">
          <Section level="h2">
            <Heading level="h2" id="store" title="Pinia Store" />
            <p className="text-krds-gray-70 mt-4 mb-4">
              Zustand 대신 Pinia를 사용합니다. Composition API 스타일로
              작성합니다.
            </p>
            <CodeBlock code={storeCode} language="typescript" />

            <Subsection level="h3">
              <Heading level="h3" id="store-usage" title="Store 사용법" />
              <CodeBlock
                code={`<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useBoardStore } from '@/features/board/stores/boardStore'

const store = useBoardStore()

// 반응형으로 사용하려면 storeToRefs 사용
const { searchKeyword, skip, limit } = storeToRefs(store)

// 액션은 직접 호출
store.setSearchKeyword('검색어')
store.nextPage()
</script>`}
                language="vue"
              />
            </Subsection>
          </Section>
        </TabsContent>

        <TabsContent value="composables">
          <Section level="h2">
            <Heading
              level="h2"
              id="composables"
              title="Vue Query Composables"
            />
            <p className="text-krds-gray-70 mt-4 mb-4">
              React Query 훅을 Vue Composable로 변환합니다.
            </p>
            <CodeBlock code={composablesCode} language="typescript" />

            <Alert variant="info" className="mt-4">
              <strong>핵심 차이점:</strong>
              <br />- <Code>queryKey</Code>를 <Code>computed()</Code>로 감싸서
              반응형으로 만듦
              <br />- Store 값이 변경되면 자동으로 쿼리가 다시 실행됨
            </Alert>
          </Section>
        </TabsContent>

        <TabsContent value="components">
          <Section level="h2">
            <Heading level="h2" id="list-component" title="게시글 목록" />
            <CodeBlock code={boardListComponent} language="vue" />
          </Section>

          <Section level="h2">
            <Heading level="h2" id="card-component" title="게시글 카드" />
            <CodeBlock code={postCardComponent} language="vue" />
          </Section>

          <Section level="h2">
            <Heading level="h2" id="detail-component" title="게시글 상세" />
            <CodeBlock code={postDetailComponent} language="vue" />
          </Section>
        </TabsContent>
      </Tabs>

      <PageNavigation
        prev={{ title: 'Vue 시작하기', href: '/kits/vue/getting-started' }}
        next={{ title: 'Auth Kit (Vue)', href: '/kits/vue/auth' }}
      />
    </>
  );
}

// apps/docs/src/app/kits/board/page.tsx
'use client';

import {
  PageSection as Section,
  Heading,
  Subsection,
  PageNavigation,
} from '@/components/content';
import {
  Code,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Badge,
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
  List,
  ListItem,
} from '@hanui/react';

// 타입 정의 코드 (DummyJSON 기준)
const typeCode = `// 게시글 타입 (DummyJSON 응답 형식)
export interface Post {
  id: number
  title: string
  body: string
  tags: string[]
  reactions: { likes: number; dislikes: number }
  views: number
  userId: number
}

// 게시글 목록 응답 (DummyJSON 형식)
export interface PostListResponse {
  posts: Post[]
  total: number
  skip: number
  limit: number
}

// 게시글 작성/수정 폼 데이터
export interface PostFormData {
  title: string
  body: string
  userId: number
  tags?: string[]
}

// 게시글 목록 조회 파라미터
export interface PostListParams {
  skip?: number
  limit?: number
  search?: string
  sortBy?: 'latest' | 'views'
}`;

// API 코드 (DummyJSON 사용)
const apiCode = `import axios from 'axios'
import type { Post, PostListResponse, PostFormData, PostListParams } from './types'

// 🔗 DummyJSON 무료 API (테스트용)
const API_URL = 'https://dummyjson.com'

const api = axios.create({
  baseURL: API_URL,
  headers: { 'Content-Type': 'application/json' },
})

// 게시글 목록 조회
export async function getPosts(params?: PostListParams): Promise<PostListResponse> {
  // 검색어가 있으면 검색 API 사용
  if (params?.search) {
    const { data } = await api.get('/posts/search', {
      params: { q: params.search, limit: params.limit, skip: params.skip }
    })
    return data
  }
  const { data } = await api.get('/posts', {
    params: { limit: params?.limit || 10, skip: params?.skip || 0 }
  })
  return data
}

// 게시글 상세 조회
export async function getPost(id: number): Promise<Post> {
  const { data } = await api.get(\`/posts/\${id}\`)
  return data
}

// 게시글 작성 (DummyJSON은 실제 저장 안 됨, 응답만 반환)
export async function createPost(formData: PostFormData): Promise<Post> {
  const { data } = await api.post('/posts/add', formData)
  return data
}

// 게시글 수정
export async function updatePost(id: number, formData: PostFormData): Promise<Post> {
  const { data } = await api.put(\`/posts/\${id}\`, formData)
  return data
}

// 게시글 삭제
export async function deletePost(id: number): Promise<Post & { isDeleted: boolean }> {
  const { data } = await api.delete(\`/posts/\${id}\`)
  return data
}`;

// React Query Hooks 코드
const hooksCode = `import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { getPosts, getPost, createPost, updatePost, deletePost } from './api'
import type { PostListParams, PostFormData } from './types'

// Query Keys
export const boardKeys = {
  all: ['board'] as const,
  lists: () => [...boardKeys.all, 'list'] as const,
  list: (params: PostListParams) => [...boardKeys.lists(), params] as const,
  details: () => [...boardKeys.all, 'detail'] as const,
  detail: (id: number) => [...boardKeys.details(), id] as const,
}

// 게시글 목록 조회
export function usePosts(params?: PostListParams) {
  return useQuery({
    queryKey: boardKeys.list(params || {}),
    queryFn: () => getPosts(params),
  })
}

// 게시글 상세 조회
export function usePost(id: number) {
  return useQuery({
    queryKey: boardKeys.detail(id),
    queryFn: () => getPost(id),
    enabled: !!id,
  })
}

// 게시글 작성
export function useCreatePost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: createPost,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: boardKeys.lists() })
    },
  })
}

// 게시글 수정
export function useUpdatePost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: PostFormData }) => updatePost(id, data),
    onSuccess: (_, { id }) => {
      queryClient.invalidateQueries({ queryKey: boardKeys.lists() })
      queryClient.invalidateQueries({ queryKey: boardKeys.detail(id) })
    },
  })
}

// 게시글 삭제
export function useDeletePost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: deletePost,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: boardKeys.lists() })
    },
  })
}`;

// Zustand Store 코드 (UI 상태 관리)
const storeCode = `import { create } from 'zustand'

interface BoardState {
  // 검색/필터 상태
  searchKeyword: string
  sortBy: 'latest' | 'views'
  skip: number  // DummyJSON은 skip 사용
  limit: number

  // 선택된 항목
  selectedIds: number[]

  // 모달 상태
  isDeleteModalOpen: boolean
  deleteTargetId: number | null

  // Actions
  setSearchKeyword: (keyword: string) => void
  setSortBy: (sortBy: 'latest' | 'views') => void
  setSkip: (skip: number) => void
  nextPage: () => void
  prevPage: () => void
  resetFilters: () => void
  toggleSelect: (id: number) => void
  selectAll: (ids: number[]) => void
  clearSelection: () => void
  openDeleteModal: (id: number) => void
  closeDeleteModal: () => void
}

export const useBoardStore = create<BoardState>((set, get) => ({
  searchKeyword: '',
  sortBy: 'latest',
  skip: 0,
  limit: 10,
  selectedIds: [],
  isDeleteModalOpen: false,
  deleteTargetId: null,

  setSearchKeyword: (keyword) => set({ searchKeyword: keyword, skip: 0 }),
  setSortBy: (sortBy) => set({ sortBy, skip: 0 }),
  setSkip: (skip) => set({ skip }),
  nextPage: () => set((state) => ({ skip: state.skip + state.limit })),
  prevPage: () => set((state) => ({ skip: Math.max(0, state.skip - state.limit) })),
  resetFilters: () => set({ searchKeyword: '', sortBy: 'latest', skip: 0 }),
  toggleSelect: (id) =>
    set((state) => ({
      selectedIds: state.selectedIds.includes(id)
        ? state.selectedIds.filter((i) => i !== id)
        : [...state.selectedIds, id],
    })),
  selectAll: (ids) => set({ selectedIds: ids }),
  clearSelection: () => set({ selectedIds: [] }),
  openDeleteModal: (id) => set({ isDeleteModalOpen: true, deleteTargetId: id }),
  closeDeleteModal: () => set({ isDeleteModalOpen: false, deleteTargetId: null }),
}))`;

// 사용 예시 코드
const usageCode = `'use client'

import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { usePosts, useCreatePost } from '@/hooks/useBoard'
import { useBoardStore } from '@/store/boardStore'

const queryClient = new QueryClient()

function BoardList() {
  const { skip, limit, searchKeyword, nextPage, prevPage } = useBoardStore()
  const { data, isLoading } = usePosts({ skip, limit, search: searchKeyword })

  if (isLoading) return <div>로딩 중...</div>

  return (
    <div>
      {/* 게시글 목록 */}
      {data?.posts.map((post) => (
        <article key={post.id} className="p-4 border-b">
          <h2 className="font-bold">{post.title}</h2>
          <p className="text-gray-600 text-sm">{post.body.slice(0, 100)}...</p>
          <div className="flex gap-4 mt-2 text-xs text-gray-500">
            <span>👁 {post.views}</span>
            <span>👍 {post.reactions.likes}</span>
          </div>
        </article>
      ))}

      {/* 페이지네이션 */}
      <div className="flex gap-2 mt-4">
        <button onClick={prevPage} disabled={skip === 0}>이전</button>
        <span>총 {data?.total}개 중 {skip + 1}-{skip + (data?.posts.length || 0)}</span>
        <button onClick={nextPage} disabled={skip + limit >= (data?.total || 0)}>다음</button>
      </div>
    </div>
  )
}

export default function BoardPage() {
  return (
    <QueryClientProvider client={queryClient}>
      <BoardList />
    </QueryClientProvider>
  )
}`;

export default function BoardKitPage() {
  return (
    <>
      <Heading
        level="h1"
        title="Board Kit"
        description="게시판 기능 키트. API 주소만 바꾸면 바로 동작합니다."
      />

      <Tabs defaultValue="overview">
        <TabsList>
          <TabsTrigger value="overview">개요</TabsTrigger>
          <TabsTrigger value="api">API 레퍼런스</TabsTrigger>
        </TabsList>

        {/* 개요 탭 */}
        <TabsContent value="overview">
          {/* 기술 스택 */}
          <Section level="h2">
            <Heading level="h2" id="tech-stack" title="기술 스택" />
            <div className="flex flex-wrap gap-2 mt-4">
              <Badge variant="outline-gray">Zustand</Badge>
              <Badge variant="outline-gray">React Query</Badge>
              <Badge variant="outline-gray">Axios</Badge>
              <Badge variant="outline-gray">React Hook Form</Badge>
              <Badge variant="outline-gray">Zod</Badge>
              <Badge variant="outline-gray">TypeScript</Badge>
            </div>
          </Section>

          {/* 기능 */}
          <Section level="h2">
            <Heading level="h2" id="features" title="기능" />
            <List className="mt-4">
              <ListItem>목록 조회 (페이지네이션, 검색, 정렬)</ListItem>
              <ListItem>상세 조회 (조회수, 첨부파일)</ListItem>
              <ListItem>게시글 작성 (폼 유효성 검사)</ListItem>
              <ListItem>게시글 수정 (기존 데이터 불러오기)</ListItem>
              <ListItem>게시글 삭제 (확인 모달)</ListItem>
            </List>
          </Section>

          {/* 파일 구조 */}
          <Section level="h2">
            <Heading level="h2" id="file-structure" title="파일 구조" />
            <Code variant="block" language="bash">
              {`src/
├── api/
│   └── board.ts          # API 함수 (CRUD)
├── hooks/
│   └── useBoard.ts       # React Query 훅
├── store/
│   └── boardStore.ts     # Zustand (UI 상태)
├── components/board/
│   ├── BoardList.tsx     # 목록
│   ├── BoardItem.tsx     # 목록 아이템
│   ├── BoardDetail.tsx   # 상세
│   ├── BoardForm.tsx     # 작성/수정 폼
│   └── DeleteModal.tsx   # 삭제 확인 모달
└── types/
    └── board.ts          # 타입 정의`}
            </Code>
          </Section>

          {/* 설치 */}
          <Section level="h2">
            <Heading level="h2" id="installation" title="설치" />

            <Subsection level="h3">
              <Heading level="h3" title="1. 의존성 설치" />
              <Code variant="block" language="bash">
                {`npm install axios zustand @tanstack/react-query react-hook-form @hookform/resolvers zod`}
              </Code>
            </Subsection>

            <Subsection level="h3">
              <Heading level="h3" title="2. 코드 복사" />
              <p className="text-krds-gray-70">
                아래 코드 탭에서 필요한 파일들을 복사합니다.
              </p>
            </Subsection>

            <Subsection level="h3">
              <Heading level="h3" title="3. API 주소 변경" />
              <Code variant="block" language="typescript">
                {`// api/board.ts
const API_URL = 'https://your-api.com/api'  // 실제 서버 주소로 변경`}
              </Code>
            </Subsection>
          </Section>

          {/* 코드 */}
          <Section level="h2">
            <Heading level="h2" id="code" title="코드" />
            <Tabs defaultValue="types">
              <TabsList>
                <TabsTrigger value="types">types.ts</TabsTrigger>
                <TabsTrigger value="api">api.ts</TabsTrigger>
                <TabsTrigger value="hooks">hooks.ts</TabsTrigger>
                <TabsTrigger value="store">store.ts</TabsTrigger>
              </TabsList>

              <TabsContent value="types">
                <Code variant="block" language="typescript">
                  {typeCode}
                </Code>
              </TabsContent>
              <TabsContent value="api">
                <Code variant="block" language="typescript">
                  {apiCode}
                </Code>
              </TabsContent>
              <TabsContent value="hooks">
                <Code variant="block" language="typescript">
                  {hooksCode}
                </Code>
              </TabsContent>
              <TabsContent value="store">
                <Code variant="block" language="typescript">
                  {storeCode}
                </Code>
              </TabsContent>
            </Tabs>
          </Section>

          {/* 사용 예시 */}
          <Section level="h2">
            <Heading level="h2" id="usage" title="사용 예시" />
            <Code variant="block" language="tsx">
              {usageCode}
            </Code>
          </Section>

          {/* 접근성 */}
          <Section level="h2">
            <Heading level="h2" id="accessibility" title="접근성" />
            <List className="mt-4">
              <ListItem>
                게시글 목록은 시맨틱 마크업(<Code>article</Code>,{' '}
                <Code>h2</Code>) 사용 권장
              </ListItem>
              <ListItem>
                페이지네이션에 <Code>aria-label</Code> 및{' '}
                <Code>aria-current</Code> 속성 적용
              </ListItem>
              <ListItem>
                삭제 모달은 <Code>AlertDialog</Code> 컴포넌트 사용으로 키보드
                트랩 및 포커스 관리 자동 처리
              </ListItem>
              <ListItem>
                폼 유효성 검사 오류 메시지는 <Code>aria-describedby</Code>로
                연결
              </ListItem>
              <ListItem>
                로딩 상태는 <Code>aria-busy</Code> 속성으로 스크린 리더에 전달
              </ListItem>
            </List>
          </Section>
        </TabsContent>

        {/* API 레퍼런스 탭 */}
        <TabsContent value="api">
          {/* API 함수 */}
          <Section level="h2">
            <Heading level="h2" id="api-functions" title="API 함수" />
            <Table small className="mt-4">
              <TableHeader>
                <TableRow>
                  <TableHead>함수</TableHead>
                  <TableHead>파라미터</TableHead>
                  <TableHead>반환값</TableHead>
                  <TableHead>설명</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>
                    <Code>getPosts</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">PostListParams?</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">PostListResponse</Code>
                  </TableCell>
                  <TableCell>게시글 목록 조회</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>getPost</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">id: number</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">Post</Code>
                  </TableCell>
                  <TableCell>게시글 상세 조회</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>createPost</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">PostFormData</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">Post</Code>
                  </TableCell>
                  <TableCell>게시글 작성</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>updatePost</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">id, PostFormData</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">Post</Code>
                  </TableCell>
                  <TableCell>게시글 수정</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>deletePost</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">id: number</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">void</Code>
                  </TableCell>
                  <TableCell>게시글 삭제</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </Section>

          {/* React Query Hooks */}
          <Section level="h2">
            <Heading level="h2" id="hooks" title="React Query Hooks" />
            <Table small className="mt-4">
              <TableHeader>
                <TableRow>
                  <TableHead>Hook</TableHead>
                  <TableHead>파라미터</TableHead>
                  <TableHead>설명</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>
                    <Code>usePosts</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">PostListParams?</Code>
                  </TableCell>
                  <TableCell>게시글 목록 조회 (캐싱, 자동 리페치)</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>usePost</Code>
                  </TableCell>
                  <TableCell>
                    <Code className="text-xs">id: number</Code>
                  </TableCell>
                  <TableCell>게시글 상세 조회</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>useCreatePost</Code>
                  </TableCell>
                  <TableCell>-</TableCell>
                  <TableCell>게시글 작성 뮤테이션</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>useUpdatePost</Code>
                  </TableCell>
                  <TableCell>-</TableCell>
                  <TableCell>게시글 수정 뮤테이션</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Code>useDeletePost</Code>
                  </TableCell>
                  <TableCell>-</TableCell>
                  <TableCell>게시글 삭제 뮤테이션</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </Section>

          {/* Zustand Store */}
          <Section level="h2">
            <Heading level="h2" id="store" title="Zustand Store" />

            <Subsection level="h3">
              <Heading level="h3" title="State" />
              <Table small className="mt-4">
                <TableHeader>
                  <TableRow>
                    <TableHead>속성</TableHead>
                    <TableHead>타입</TableHead>
                    <TableHead>설명</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <Code>searchKeyword</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">string</Code>
                    </TableCell>
                    <TableCell>검색어</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>sortBy</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">
                        'latest' | 'oldest' | 'views'
                      </Code>
                    </TableCell>
                    <TableCell>정렬 기준</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>page</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">number</Code>
                    </TableCell>
                    <TableCell>현재 페이지</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>selectedIds</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">number[]</Code>
                    </TableCell>
                    <TableCell>선택된 게시글 ID 목록</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>isDeleteModalOpen</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">boolean</Code>
                    </TableCell>
                    <TableCell>삭제 모달 표시 여부</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </Subsection>

            <Subsection level="h3">
              <Heading level="h3" title="Actions" />
              <Table small className="mt-4">
                <TableHeader>
                  <TableRow>
                    <TableHead>함수</TableHead>
                    <TableHead>파라미터</TableHead>
                    <TableHead>설명</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <Code>setSearchKeyword</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">keyword: string</Code>
                    </TableCell>
                    <TableCell>검색어 설정 (페이지 1로 리셋)</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>setSortBy</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">sortBy</Code>
                    </TableCell>
                    <TableCell>정렬 기준 설정</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>setPage</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">page: number</Code>
                    </TableCell>
                    <TableCell>페이지 변경</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>toggleSelect</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">id: number</Code>
                    </TableCell>
                    <TableCell>게시글 선택 토글</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Code>openDeleteModal</Code>
                    </TableCell>
                    <TableCell>
                      <Code className="text-xs">id: number</Code>
                    </TableCell>
                    <TableCell>삭제 모달 열기</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </Subsection>
          </Section>

          {/* 타입 정의 */}
          <Section level="h2">
            <Heading level="h2" id="types" title="타입 정의" />
            <Code variant="block" language="typescript">
              {typeCode}
            </Code>
          </Section>
        </TabsContent>
      </Tabs>

      <PageNavigation
        prev={{ title: 'Getting Started', href: '/kits/getting-started' }}
        next={{ title: 'Auth Kit', href: '/kits/auth' }}
      />
    </>
  );
}
