// packages/react/src/components/code.tsx
'use client';

import * as React from 'react';
import { useEffect, useState } from 'react';
import { codeToHtml } from 'shiki';
import { File, Copy, Check } from 'lucide-react';
import { cn } from '../lib/utils';

export interface CodeProps extends React.HTMLAttributes<HTMLElement> {
  // Code Props
  variant?: 'inline' | 'block'; // 코드 타입 (기본값: inline)
  size?: 'sm' | 'default' | 'lg'; // 크기 (inline 전용, 기본값: default)
  language?: string; // 프로그래밍 언어 (Syntax highlighting, block 전용)
  showLineNumbers?: boolean; // 줄 번호 표시 (block + language 전용, 기본값: true)
  fileName?: string; // 파일명 표시 (block + language 전용)
  theme?: string; // Shiki 테마 (block + language 전용, 기본값: github-dark)
}

const sizeStyles = {
  // 인라인 코드 크기 스타일
  sm: 'text-krds-body-xs px-1 py-0.5',
  default: 'text-krds-body-sm px-1.5 py-0.5',
  lg: 'text-krds-body-md px-2 py-1',
} as const;

export const Code = React.forwardRef<HTMLElement, CodeProps>( // KRDS 코드 컴포넌트 (인라인/블록, Syntax highlighting, 복사 기능)
  (
    {
      variant = 'inline',
      size = 'default',
      language,
      showLineNumbers = true,
      fileName,
      theme = 'github-dark',
      className,
      children,
      ...props
    },
    ref
  ) => {
    const [copied, setCopied] = React.useState(false);
    const [html, setHtml] = useState('');

    const code = typeof children === 'string' ? children : '';

    useEffect(() => {
      // Syntax highlighting (block + language)
      if (variant === 'block' && language) {
        const highlightCode = async () => {
          const highlighted = await codeToHtml(code, {
            lang: language,
            theme: theme,
          });
          setHtml(highlighted);
        };

        highlightCode();
      }
    }, [code, language, theme, variant]);

    const handleCopy = async () => {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    };

    if (variant === 'block' && language) {
      // Block variant (Syntax highlighting 적용)
      if (!html) {
        return (
          <div className={cn('relative group', className)}>
            <div className="overflow-x-auto rounded-lg bg-krds-gray-90 p-5">
              <div className="animate-pulse">
                <div className="h-4 bg-krds-gray-70 rounded w-3/4 mb-2"></div>
                <div className="h-4 bg-krds-gray-70 rounded w-1/2"></div>
              </div>
            </div>
          </div>
        );
      }

      return (
        <div className={cn('relative group', className)}>
          {fileName && (
            <div className="flex items-center gap-2 px-4 py-2 bg-krds-gray-90 border-b border-krds-gray-70 rounded-t-lg">
              <File className="w-3.5 h-3.5 text-krds-gray-40" />
              <span className="text-xs text-krds-gray-40 font-mono">
                {fileName}
              </span>
            </div>
          )}
          <div className="relative">
            <button
              onClick={handleCopy}
              className={cn(
                'absolute top-4 right-3 p-2 rounded-md transition-all z-10',
                'bg-krds-gray-70 hover:bg-krds-gray-60',
                'text-krds-gray-10 opacity-0 group-hover:opacity-100'
              )}
              aria-label="Copy code"
            >
              {copied ? (
                <Check className="w-4 h-4" />
              ) : (
                <Copy className="w-4 h-4" />
              )}
            </button>
            <div
              className={cn(
                'overflow-x-auto',
                fileName ? 'rounded-b-lg' : 'rounded-lg',
                showLineNumbers ? 'code-with-line-numbers' : ''
              )}
              dangerouslySetInnerHTML={{ __html: html }}
            />
          </div>
        </div>
      );
    }

    if (variant === 'block') {
      // Block variant (단순, Syntax highlighting 없음)
      return (
        <div className="relative group">
          <pre
            ref={ref as React.Ref<HTMLPreElement>}
            className={cn(
              'font-mono bg-krds-primary-5 rounded-lg p-4 overflow-x-auto',
              'text-krds-primary-70 border border-krds-primary-20',
              className
            )}
            {...props}
          >
            <code>{children}</code>
          </pre>
          <button
            onClick={handleCopy}
            className={cn(
              'absolute top-4 right-3 p-2 rounded-md transition-all z-10',
              'bg-krds-primary-10 hover:bg-krds-primary-20 border border-krds-primary-30',
              'text-krds-primary-70 opacity-0 group-hover:opacity-100'
            )}
            aria-label="Copy code"
          >
            {copied ? (
              <Check className="w-4 h-4" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
          </button>
        </div>
      );
    }

    return (
      // Inline variant
      <code
        ref={ref}
        className={cn(
          'font-mono bg-krds-primary-5 text-krds-primary-70 rounded border border-krds-primary-20',
          sizeStyles[size],
          className
        )}
        {...props}
      >
        {children}
      </code>
    );
  }
);

Code.displayName = 'Code';

// packages/vue/src/components/Code.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { File, Copy, Check } from 'lucide-vue-next';
import { cn } from '../lib/utils';

const sizeStyles = {
  sm: 'text-krds-body-xs px-1 py-0.5',
  default: 'text-krds-body-sm px-1.5 py-0.5',
  lg: 'text-krds-body-md px-2 py-1',
} as const;

const props = withDefaults(
  defineProps<{
    variant?: 'inline' | 'block';
    size?: 'sm' | 'default' | 'lg';
    language?: string;
    showLineNumbers?: boolean;
    fileName?: string;
    theme?: string;
    code?: string;
    class?: string;
  }>(),
  {
    variant: 'inline',
    size: 'default',
    showLineNumbers: true,
    theme: 'github-dark',
  }
);

const copied = ref(false);
const html = ref('');
const loading = ref(false);

const handleCopy = async () => {
  const codeToCopy = props.code || '';
  await navigator.clipboard.writeText(codeToCopy);
  copied.value = true;
  setTimeout(() => {
    copied.value = false;
  }, 2000);
};

const highlightCode = async () => {
  if (props.variant === 'block' && props.language && props.code) {
    loading.value = true;
    try {
      const { codeToHtml } = await import('shiki');
      const highlighted = await codeToHtml(props.code, {
        lang: props.language,
        theme: props.theme,
      });
      html.value = highlighted;
    } catch {
      html.value = '';
    } finally {
      loading.value = false;
    }
  }
};

watch(
  () => [props.code, props.language, props.theme, props.variant],
  () => {
    highlightCode();
  },
  { immediate: true }
);

const inlineClasses = computed(() =>
  cn(
    'font-mono bg-krds-primary-5 text-krds-primary-70 rounded border border-krds-primary-20',
    sizeStyles[props.size],
    props.class
  )
);

const blockClasses = computed(() =>
  cn(
    'font-mono bg-krds-primary-5 rounded-lg p-4 overflow-x-auto',
    'text-krds-primary-70 border border-krds-primary-20',
    props.class
  )
);
</script>

<template>
  <!-- Block variant with syntax highlighting -->
  <div v-if="variant === 'block' && language" :class="cn('relative group', props.class)">
    <!-- Loading state -->
    <div v-if="loading" class="overflow-x-auto rounded-lg bg-krds-gray-90 p-5">
      <div class="animate-pulse">
        <div class="h-4 bg-krds-gray-70 rounded w-3/4 mb-2"></div>
        <div class="h-4 bg-krds-gray-70 rounded w-1/2"></div>
      </div>
    </div>

    <!-- Highlighted code -->
    <template v-else>
      <div
        v-if="fileName"
        class="flex items-center gap-2 px-4 py-2 bg-krds-gray-90 border-b border-krds-gray-70 rounded-t-lg"
      >
        <File class="w-3.5 h-3.5 text-krds-gray-40" />
        <span class="text-xs text-krds-gray-40 font-mono">{{ fileName }}</span>
      </div>
      <div class="relative">
        <button
          @click="handleCopy"
          :class="cn(
            'absolute top-3 right-3 p-2 rounded-md transition-all z-10',
            'bg-krds-gray-70 hover:bg-krds-gray-60',
            'text-krds-gray-10 opacity-0 group-hover:opacity-100'
          )"
          aria-label="Copy code"
        >
          <Check v-if="copied" class="w-4 h-4" />
          <Copy v-else class="w-4 h-4" />
        </button>
        <div
          :class="cn(
            'overflow-x-auto',
            fileName ? 'rounded-b-lg' : 'rounded-lg',
            showLineNumbers ? 'code-with-line-numbers' : ''
          )"
          v-html="html"
        />
      </div>
    </template>
  </div>

  <!-- Block variant without syntax highlighting -->
  <div v-else-if="variant === 'block'" class="relative group">
    <pre :class="blockClasses"><code><slot>{{ code }}</slot></code></pre>
    <button
      @click="handleCopy"
      :class="cn(
        'absolute top-3 right-3 p-2 rounded-md transition-all z-10',
        'bg-krds-primary-10 hover:bg-krds-primary-20 border border-krds-primary-30',
        'text-krds-primary-70 opacity-0 group-hover:opacity-100'
      )"
      aria-label="Copy code"
    >
      <Check v-if="copied" class="w-4 h-4" />
      <Copy v-else class="w-4 h-4" />
    </button>
  </div>

  <!-- Inline variant -->
  <code v-else :class="inlineClasses">
    <slot>{{ code }}</slot>
  </code>
</template>
